export type RelationshipGroup="spouse"|"child"|"parent"|"sibling"|"dependent";
export type FamilyRelationship="spouse"|"wife"|"husband"|"son"|"daughter"|"children"|"father"|"mother"|"parents"|"brother"|"sister"|"siblings"|"other_dependent";
export type SemanticEntity={kind:"person"|"company"|"property"|"employment"|"document"|"service_subject"|"unknown";relationship:FamilyRelationship|null;relationship_group:RelationshipGroup|null};
export type SemanticAction="issue"|"renew"|"amend"|"cancel"|"transfer"|"sponsor"|null;
export type SemanticContext={relationship:FamilyRelationship|null;relationship_group:RelationshipGroup|null;entity:SemanticEntity;service_slug:string|null;authority_key:string|null;jurisdiction:string|null;intent:string|null;service_family:string|null;action:SemanticAction};
const norm=(v:unknown)=>String(v??"").toLowerCase().normalize("NFKD").replace(/[\u064B-\u065F\u0670]/g,"").replace(/[أإآ]/g,"ا").replace(/ى/g,"ي").replace(/ة/g,"ه").replace(/[^\p{L}\p{N}]+/gu," ").replace(/\s+/g," ").trim();
const aliases:Record<FamilyRelationship,string[]>={
 parents:["الوالدين","والداي","امي وابويا","امي وابي","ابويا وامي","my parents","parents","mom and dad"],mother:["والدتي","امي","الوالده","ماما","my mother","mother","mom","mum"],father:["والدي","ابي","ابويا","الوالد","بابا","my father","father","dad"],
 wife:["زوجتي","مراتي","المدام","wife","my wife"],husband:["زوجي","جوزي","husband","my husband"],spouse:["زوجه","زوج","spouse","partner"],
 children:["اولادي","عيالي","ابنائي","اطفالي","my children","children","kids","my kids"],daughter:["بنتي","ابنتي","my daughter","daughter"],son:["ابني","ولدي","my son","son"],
 siblings:["اخواتي","اخوتي","اخواني","siblings","my siblings"],brother:["اخي","اخويا","my brother","brother"],sister:["اختي","my sister","sister"],other_dependent:["معالي","تابعي","مكفولي","dependent","my dependent"]};
const group=(r:FamilyRelationship|null):RelationshipGroup|null=>!r?null:(["wife","husband","spouse"].includes(r)?"spouse":["son","daughter","children"].includes(r)?"child":["father","mother","parents"].includes(r)?"parent":["brother","sister","siblings"].includes(r)?"sibling":"dependent");
export function detectRelationship(value:unknown):FamilyRelationship|null{const t=" "+norm(value)+" ";let best:{r:FamilyRelationship;n:number}|null=null;const tokens=norm(value).split(" ").filter(Boolean);for(const [r,words] of Object.entries(aliases) as [FamilyRelationship,string[]][])for(const w of words){const n=norm(w);const clitic=n&&!n.includes(" ")&&tokens.some(token=>token===n||(["و","ف","ب","ك","ل"].includes(token[0])&&token.slice(1)===n));if(n&&(t.includes(" "+n+" ")||clitic)&&(!best||n.length>best.n))best={r,n:n.length};}return best?.r??null;}
export function relationshipGroup(r:FamilyRelationship|null){return group(r);}
export function detectAction(value:unknown):SemanticAction{const t=" "+norm(value)+" ";const words=t.trim().split(" ").filter(Boolean);const correctionRenew=words.some(x=>x==="تجديد"||x==="اجدد"||x==="renew")&&words.some(x=>x==="بدل"||x==="instead")&&words.some(x=>x==="اصدار"||x==="issue");if(correctionRenew)return "renew";const checks:[SemanticAction,string[]][]=[["renew",["اجدد","تجديد","renew"]],["amend",["اعدل","تعديل","amend","modify"]],["cancel",["الغي","الغاء","cancel"]],["transfer",["انقل","نقل","تحويل","transfer","move"]],["sponsor",["اكفل","كفاله","sponsor","sponsorship"]],["issue",["اصدار","اريد اقامه","عايز اقامه","احتاج اقامه","issue","new residence","new visa"]]];for(const [a,words] of checks)if(words.some(w=>t.includes(" "+norm(w)+" ")))return a;return null;}
export function detectJurisdiction(value:unknown):string|null{const t=norm(value);const m:[string,string[]][]=[["AE-DU",["دبي","dubai"]],["AE-AZ",["ابوظبي","ابو ظبي","abu dhabi","abudhabi"]],["AE-SH",["الشارقه","sharjah"]],["AE-AJ",["عجمان","ajman"]],["AE-RK",["راس الخيمه","ras al khaimah","rak"]],["AE-UQ",["ام القيوين","umm al quwain","uaq"]],["AE-FU",["الفجيره","fujairah"]]];for(const [c,a] of m)if(a.some(x=>t.includes(norm(x))))return c;return null;}
export function relationshipCompatibility(identity:unknown,r:FamilyRelationship|null):number{if(!r)return 0;const t=norm(identity),g=group(r);const parent=/والد|اب|ام|parent|mother|father/.test(t),family=/family|اسر|عائل|زوج|spouse|wife|husband|dependent|residen/.test(t);if(g==="parent")return parent?4:family?1:0;if(parent)return -4;return family?3:0;}
export function mergeSemanticContext(latestTurn:string,prior:Partial<SemanticContext>|null,fallbackGoal:string,opts:{newTopic?:boolean;explicitService?:string|null;explicitAuthority?:string|null;intent?:string|null;serviceFamily?:string|null}={}):SemanticContext{const explicitRelationship=detectRelationship(latestTurn);const priorRelationship=(prior?.relationship??null) as FamilyRelationship|null;const relationship=opts.newTopic&&!explicitRelationship?null:(explicitRelationship??priorRelationship??detectRelationship(fallbackGoal));const explicitJurisdiction=detectJurisdiction(latestTurn);const carriedJurisdiction=opts.newTopic?null:(prior?.jurisdiction||null);const jurisdiction=explicitJurisdiction||carriedJurisdiction||detectJurisdiction(fallbackGoal);const action=detectAction(latestTurn)??(opts.newTopic?null:(prior?.action??null));const entity:SemanticEntity=relationship?{kind:"person",relationship,relationship_group:group(relationship)}:(opts.newTopic?{kind:"unknown",relationship:null,relationship_group:null}:(prior?.entity??{kind:"unknown",relationship:null,relationship_group:null}));return {relationship,relationship_group:group(relationship),entity,service_slug:opts.explicitService??(opts.newTopic?null:(prior?.service_slug??null)),authority_key:opts.explicitAuthority??(opts.newTopic?null:(prior?.authority_key??null)),jurisdiction,intent:opts.intent??(opts.newTopic?null:(prior?.intent??null)),service_family:opts.serviceFamily??(opts.newTopic?null:(prior?.service_family??null)),action};}
export function semanticInvariants(before:SemanticContext,after:SemanticContext,latestTurn:string){const explicit=detectRelationship(latestTurn);return {relationship_preserved_without_explicit_change:!!explicit||before.relationship===after.relationship,explicit_relationship_wins:!explicit||after.relationship===explicit,jurisdiction_change_does_not_mutate_relationship:!detectJurisdiction(latestTurn)||!!explicit||before.relationship===after.relationship};}
