import test from 'node:test';import assert from 'node:assert/strict';import {auditCustomerService,summarizeCustomerAudit} from '../../src/publication/customer-catalog-audit.mjs';
test('publication verification never turns missing customer fields into full acceptance',()=>{
 const row=auditCustomerService({id:'one',slug:'one',name:{ar:'خدمة',en:'Service'},verificationStatus:'VERIFIED',verification:{detailsVerified:true,feesVerified:true},governmentFees:{text:'NOT_OFFICIALLY_PUBLISHED'},internalRoute:'/services/one/'});
 assert.equal(row.fields.fees,'MISSING');assert.equal(row.fields.aliases,'MISSING');assert.equal(row.fields.ai_discoverability,'MISSING');assert.equal(row.fullyVerified,false);assert.equal(summarizeCustomerAudit([row]).fullyVerifiedServices,0);
});
test('a present unverified government value remains unverified',()=>{const row=auditCustomerService({governmentFees:{text:'unverified fee'},verification:{feesVerified:false}});assert.equal(row.fields.fees,'NOT_VERIFIED');});

test('Arabic placeholders remain missing even with recorded verification flags',()=>{for(const placeholder of ['غير موثق بعد','غير موثق في سجل الكتالوج','غير متوفر','TBD','  غير موثق بعد  ']){const row=auditCustomerService({conditions:placeholder,governmentFees:{text:placeholder},processingTime:{text:placeholder},documents:{items:[placeholder]},verification:{eligibilityVerified:true,feesVerified:true,durationVerified:true,requirementsVerified:true}});for(const field of ['eligibility','fees','duration','documents','requirements'])assert.equal(row.fields[field],'MISSING',placeholder+': '+field);}});
test('a partially missing document list cannot be fully verified',()=>{const row=auditCustomerService({documents:{items:['جواز سفر ساري','غير موثق بعد']},verification:{requirementsVerified:true}});assert.equal(row.fields.documents,'MISSING');});
