import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import {detectAction,detectRelationship,detectSubjectRole,mergeSemanticContext,semanticInvariants,relationshipCompatibility,semanticDomainCompatibility} from "../../supabase/functions/public-ai-concierge/semantic-context.ts";
const catalog=JSON.parse(fs.readFileSync(new URL("../../service-matrix.json",import.meta.url),"utf8")).services;
const variants=new Map([
 ["wife",["زوجتي","مراتي","my wife"]],["husband",["زوجي","جوزي","my husband"]],["son",["ابني","ولدي","my son"]],["daughter",["بنتي","ابنتي","my daughter"]],["children",["أولادي","عيالي","my kids"]],["mother",["والدتي","أمي","ماما","my mother"]],["father",["والدي","أبي","ابويا","my father"]],["brother",["أخي","اخويا","my brother"]],["sister",["أختي","my sister"]]
]);
test("relationship aliases cover MSA Egyptian Gulf and English",()=>{for(const [expected,forms] of variants)for(const form of forms)assert.equal(detectRelationship(form),expected,form);});
test("semantic relationship is invariant under emirate service authority and short follow-ups",()=>{for(const [relationship,forms] of variants){let s=mergeSemanticContext(forms[0],null,forms[0]);for(const turn of ["دبي","أبوظبي","كم الرسوم؟","والمستندات؟","التجديد بدل الإصدار","GDRFA"]){const n=mergeSemanticContext(turn,s,turn);const inv=semanticInvariants(s,n,turn);assert.equal(inv.relationship_preserved_without_explicit_change,true,relationship+" "+turn);assert.equal(n.relationship,relationship);s=n;}}});
test("explicit relationship correction wins and only explicit evidence may change it",()=>{let s=mergeSemanticContext("أريد إقامة لزوجتي في دبي",null,"");let n=mergeSemanticContext("لا، قصدي والدتي",s,"");assert.equal(n.relationship,"mother");assert.equal(semanticInvariants(s,n,"لا، قصدي والدتي").explicit_relationship_wins,true);let follow=mergeSemanticContext("في الشارقة بدل دبي",n,"");assert.equal(follow.relationship,"mother");});
test("new topic clears stale relationship but a later explicit family reference restores it",()=>{let s=mergeSemanticContext("إقامة لابني",null,"");s=mergeSemanticContext("أريد تأسيس شركة",s,"",{newTopic:true});assert.equal(s.relationship,null);s=mergeSemanticContext("وبالنسبة لابني؟",s,"");assert.equal(s.relationship,"son");});
test("multiple family members require explicit current reference and do not let ranking mutate state",()=>{let s=mergeSemanticContext("زوجتي ووالدتي",null,"");assert.ok(["wife","mother"].includes(s.relationship));const before=s.relationship;for(const service of catalog){relationshipCompatibility(service.slug+" "+service.name+" "+service.category,s.relationship);assert.equal(s.relationship,before);}});
test("catalog-derived semantic matrix keeps service authority emirate entity relationship dimensions independent",()=>{for(const service of catalog){assert.ok(service.slug);assert.ok(service.category);assert.ok(service.authority?.slug);const relationships=[...variants.keys()];for(const r of relationships){const prior=mergeSemanticContext([...variants.get(r)][0],null,"");const after=mergeSemanticContext(service.emirate==="دبي"?"دبي":"تابع",prior,"");assert.equal(after.relationship,r,service.slug+" "+r);assert.equal(semanticInvariants(prior,after,service.emirate==="دبي"?"دبي":"تابع").relationship_preserved_without_explicit_change,true);relationshipCompatibility(service.slug+" "+service.name+" "+service.category,r);}}});
test("unverified catalog facts are never promoted by semantic layer",()=>{for(const service of catalog){const s=mergeSemanticContext(service.name,null,service.name);assert.equal("fees" in s,false);assert.equal("requirements" in s,false);assert.equal("conditions" in s,false);}});

test("service action is independent state and explicit action changes override carried action",()=>{assert.equal(detectAction("أريد أجدد إقامة زوجتي"),"renew");assert.equal(detectAction("إصدار إقامة لابني"),"issue");let s=mergeSemanticContext("إصدار إقامة لابني في دبي",null,"");assert.equal(s.action,"issue");const location=mergeSemanticContext("في أبوظبي بدل دبي",s,"");assert.equal(location.action,"issue");assert.equal(location.relationship,"son");const changed=mergeSemanticContext("أريد التجديد بدل الإصدار",location,"");assert.equal(changed.action,"renew");assert.equal(changed.relationship,"son");});
test("catalog action matrix never lets service ranking redefine semantic action",()=>{for(const service of catalog)for(const action of ["issue","renew","amend","cancel","transfer"]){const prior={...mergeSemanticContext("ابني",null,""),action};const after=mergeSemanticContext("دبي",prior,"");assert.equal(after.action,action,service.slug+" "+action);}});

test("production request path passes canonical action into ranker",()=>{const edge=fs.readFileSync(new URL("../../supabase/functions/public-ai-concierge/index.ts",import.meta.url),"utf8");const contract=fs.readFileSync(new URL("../../supabase/functions/public-ai-concierge/response-context.ts",import.meta.url),"utf8");assert.match(edge,/rank\(semanticGoal, catalog, relationship, semantic\.action\)/);assert.match(contract,/action: semantic\.action/);assert.match(edge,/goal_context:responseContext\(semantic,intelligent/);assert.match(edge,/goal_context:responseContext\(semantic,deterministic/);});

test("family relationships cannot cross into unrelated catalog domains",()=>{for(const service of catalog){for(const relationship of ["wife","husband","son","daughter","mother","father","brother","sister"]){const score=semanticDomainCompatibility(service.category,relationship);if(score>=0)assert.match(String(service.category),/family|dependent|sponsor/i,service.slug+" "+relationship);}}});


test("family sponsorship service object cannot degrade into a family-sponsored work permit",()=>{const edge=fs.readFileSync(new URL("../../supabase/functions/public-ai-concierge/index.ts",import.meta.url),"utf8");assert.match(edge,/familyResidenceSponsorship/);assert.match(edge,/work permit\|تصريح عمل[\s\S]{0,200}score -= 12000/);const s=mergeSemanticContext("أريد أن أكفل زوجتي على إقامتي",null,"");assert.equal(s.relationship,"wife");assert.equal(s.action,"sponsor");});

test("family sponsorship without emirate fails closed before selecting an emirate-specific service",()=>{const edge=fs.readFileSync(new URL("../../supabase/functions/public-ai-concierge/index.ts",import.meta.url),"utf8");assert.match(edge,/relationship && semantic\.action === "sponsor" && !semantic\.jurisdiction/);assert.match(edge,/في أي إمارة صادرة إقامة الكفيل؟/);});


test("family member set accumulates additions and correction replaces only when explicit",()=>{let s=mergeSemanticContext("أريد أكفل زوجتي",null,"");assert.deepEqual(s.family_members,["wife"]);s=mergeSemanticContext("عندي ولدين كمان",s,"");assert.equal(s.relationship,"children");assert.ok(s.family_members.includes("wife"));assert.ok(s.family_members.includes("children"));s=mergeSemanticContext("ولو أبوظبي؟",s,"");assert.equal(s.jurisdiction,"AE-AZ");assert.ok(s.family_members.includes("wife"));assert.ok(s.family_members.includes("children"));s=mergeSemanticContext("لا، قصدي والدتي",s,"");assert.equal(s.relationship,"mother");assert.deepEqual(s.family_members,["mother"]);});

const roleVariants=new Map([
["employee",["الموظف","موظف","employee"]],["employer",["صاحب العمل","جهة العمل","employer"]],["investor",["المستثمر","مستثمر","investor"]],["partner",["الشريك","شريك","partner"]],["manager",["المدير","مدير","manager"]],["owner",["المالك","صاحب الشركة","owner"]],["sponsor",["الكفيل","كفيل","sponsor"]],["dependent",["المكفول","تابع","dependent"]],["domestic_worker",["عمالة مساعدة","عاملة منزلية","domestic worker"]],["company",["الشركة","منشأة","company"]],["branch",["الفرع","فرع","branch"]]
]);
test("business subject roles cover Arabic variants and English",()=>{for(const [expected,forms] of roleVariants)for(const form of forms)assert.equal(detectSubjectRole(form),expected,form);});
test("business subject role survives deterministic multi-turn context changes",()=>{for(const [role,forms] of roleVariants){let s=mergeSemanticContext(forms[0],null,forms[0]);assert.equal(s.subject_role,role);for(const turn of ["دبي","كم الرسوم؟","والمستندات؟","GDRFA"]){s=mergeSemanticContext(turn,s,turn);assert.equal(s.subject_role,role,role+" "+turn);}}});
test("explicit business subject role change wins while topic reset clears stale role",()=>{let s=mergeSemanticContext("الموظف",null,"");assert.equal(s.subject_role,"employee");s=mergeSemanticContext("الشريك",s,"");assert.equal(s.subject_role,"partner");s=mergeSemanticContext("موضوع جديد",s,"",{newTopic:true});assert.equal(s.subject_role,null);});
test("mixed Arabic English subject references normalize deterministically",()=>{assert.equal(detectSubjectRole("عايز renew لل employee في دبي"),"employee");assert.equal(detectSubjectRole("domestic worker إقامة"),"domestic_worker");assert.equal(detectSubjectRole("فرع company في دبي"),"company");});

test("production semantic resolver propagates canonical subject role independently",()=>{const edge=fs.readFileSync(new URL("../../supabase/functions/public-ai-concierge/index.ts",import.meta.url),"utf8");assert.match(edge,/subject_role:context\?\.subject_role\?\?null/);assert.match(edge,/subject_role:merged\.subject_role/);assert.match(edge,/parsed\.subject_role=detectSubjectRole\(latestTurn\)/);});

test("production response exposes subject role so clients can carry it across turns",()=>{const contract=fs.readFileSync(new URL("../../supabase/functions/public-ai-concierge/response-context.ts",import.meta.url),"utf8");assert.match(contract,/subject_role: semantic\.subject_role/);});

test("Gulf first-person أبي is not misread as father",()=>{assert.equal(detectRelationship("أبي أفتح شركة في الشارقة"),null);assert.equal(detectSubjectRole("أبي أفتح شركة في الشارقة"),"company");});
test("natural residence issuance language resolves action",()=>{for(const q of ["عايز أعمل إقامة لمراتي","كيف اسوي اقامة للزوجة","wife visa dubai","ابي اقامه لزوجتي"])assert.equal(detectAction(q),"issue",q);});

test("English business partner is not coerced into spouse",()=>{assert.equal(detectRelationship("add partner Dubai company"),null);assert.equal(detectSubjectRole("add partner Dubai company"),"partner");});
test("Gulf أبي remains first-person before service nouns",()=>{for(const q of ["ابي رخصه اقتصاديه الشارقه","ابي اقامة ذهبية بدبي كمستثمر","ابي اسجل إيجاري","ابي اضيف شريك بالرخصة دبي"])assert.equal(detectRelationship(q),null,q);});

test("Production human variants resolve stable semantic roles and actions",()=>{
 assert.equal(detectRelationship("عاوز اطلع اقامة للمدام في دبي"),"wife");
 assert.equal(detectAction("عاوز اطلع اقامة للمدام في دبي"),"issue");
 assert.equal(detectAction("رخصتي بعجمان بتنتهي"),"renew");
 assert.equal(detectSubjectRole("add shareholder Dubai license"),"partner");
 for(const q of ["ابي اجدد اقامة الخادمة","إقامة العاملة المنزلية قربت تنتهي","domestic worker visa renewal","تجديد اقامة عامل مساعد"]) assert.equal(detectSubjectRole(q),"domestic_worker",q);
});

 test("Published English investor title preserves issue action, investor role and Dubai",()=>{const q="Issuing a golden residence permit (investors) in Dubai";const s=mergeSemanticContext(q,null,q);assert.equal(s.action,"issue");assert.equal(s.subject_role,"investor");assert.equal(s.jurisdiction,"AE-DU");assert.equal(s.relationship,null);});
