import test from "node:test";import assert from "node:assert/strict";import fs from "node:fs";
import {detectRelationship,mergeSemanticContext,semanticInvariants,relationshipCompatibility} from "../../supabase/functions/public-ai-concierge/semantic-context.ts";
const catalog=JSON.parse(fs.readFileSync(new URL("../../service-matrix.json",import.meta.url),"utf8")).services;
const variants=new Map([
 ["wife",["زوجتي","مراتي","my wife"]],["husband",["زوجي","جوزي","my husband"]],["son",["ابني","ولدي","my son"]],["daughter",["بنتي","ابنتي","my daughter"]],["children",["أولادي","عيالي","my kids"]],["mother",["والدتي","أمي","ماما","my mother"]],["father",["والدي","أبي","ابويا","my father"]],["brother",["أخي","اخويا","my brother"]],["sister",["أختي","my sister"]]
]);
test("relationship aliases cover MSA Egyptian Gulf and English",()=>{for(const [expected,forms] of variants)for(const form of forms)assert.equal(detectRelationship(form),expected,form);});
test("semantic relationship is invariant under emirate service authority and short follow-ups",()=>{for(const [relationship,forms] of variants){let s=mergeSemanticContext(forms[0],null,forms[0]);for(const turn of ["دبي","أبوظبي","كم الرسوم؟","والمستندات؟","التجديد بدل الإصدار","GDRFA"]){const n=mergeSemanticContext(turn,s,turn);const inv=semanticInvariants(s,n,turn);assert.equal(inv.relationship_preserved_without_explicit_change,true,relationship+" "+turn);assert.equal(n.relationship,relationship);s=n;}}});
test("explicit relationship correction wins and only explicit evidence may change it",()=>{let s=mergeSemanticContext("أريد إقامة لزوجتي في دبي",null,"");let n=mergeSemanticContext("لا، قصدي والدتي",s,"");assert.equal(n.relationship,"mother");assert.equal(semanticInvariants(s,n,"لا، قصدي والدتي").explicit_relationship_wins,true);let follow=mergeSemanticContext("في الشارقة بدل دبي",n,"");assert.equal(follow.relationship,"mother");});
test("new topic clears stale relationship but a later explicit family reference restores it",()=>{let s=mergeSemanticContext("إقامة لابني",null,"");s=mergeSemanticContext("أريد تأسيس شركة",s,"",{newTopic:true});assert.equal(s.relationship,null);s=mergeSemanticContext("وبالنسبة لابني؟",s,"");assert.equal(s.relationship,"son");});
test("multiple family members require explicit current reference and do not let ranking mutate state",()=>{let s=mergeSemanticContext("زوجتي ووالدتي",null,"");assert.ok(["wife","mother"].includes(s.relationship));const before=s.relationship;for(const service of catalog){relationshipCompatibility(service.slug+" "+service.name+" "+service.category,s.relationship);assert.equal(s.relationship,before);}});
test("catalog-derived semantic matrix keeps service authority emirate entity relationship dimensions independent",()=>{for(const service of catalog){assert.ok(service.slug);assert.ok(service.category);assert.ok(service.authority?.slug);const relationships=[...variants.keys()];for(const r of relationships){const prior=mergeSemanticContext([...variants.get(r)][0],null,"");const after=mergeSemanticContext(service.emirate==="دبي"?"دبي":"تابع",prior,"");assert.equal(after.relationship,r,service.slug+" "+r);assert.equal(semanticInvariants(prior,after,service.emirate==="دبي"?"دبي":"تابع").relationship_preserved_without_explicit_change,true);relationshipCompatibility(service.slug+" "+service.name+" "+service.category,r);}}});
test("unverified catalog facts are never promoted by semantic layer",()=>{for(const service of catalog){const s=mergeSemanticContext(service.name,null,service.name);assert.equal("fees" in s,false);assert.equal("requirements" in s,false);assert.equal("conditions" in s,false);}});
