(()=>{'use strict';
const STORAGE='hb-command-center-v1',ITERATIONS=250000,ENC=new TextEncoder(),DEC=new TextDecoder();let state=null,key=null,lockTimer=null;
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))),unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const clean=v=>String(v??'').trim(),today=()=>new Date(new Date().setHours(0,0,0,0));
function readVault(){try{return JSON.parse(localStorage.getItem(STORAGE)||'null')}catch{return null}}
async function derive(password,salt){const base=await crypto.subtle.importKey('raw',ENC.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:ITERATIONS,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encrypt(data,cryptoKey,salt){const iv=crypto.getRandomValues(new Uint8Array(12));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},cryptoKey,ENC.encode(JSON.stringify(data)));return{version:1,iterations:ITERATIONS,salt:b64(salt),iv:b64(iv),cipher:b64(cipher),hint:data.company?.name||'شركة',updated:new Date().toISOString()}}
async function decrypt(vault,password){const salt=unb64(vault.salt),derived=await derive(password,salt);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(vault.iv)},derived,unb64(vault.cipher));return{data:JSON.parse(DEC.decode(plain)),derived}}
async function save(){if(!state||!key)return;const current=readVault(),salt=current?unb64(current.salt):crypto.getRandomValues(new Uint8Array(16));localStorage.setItem(STORAGE,JSON.stringify(await encrypt(state,key,salt)));$('#saveState').textContent='تم الحفظ الآن';setTimeout(()=>{$('#saveState').textContent=''},1800)}
function initial(company,emirate){return{version:1,company:{name:company,emirate,license:'',authority:'',legalForm:'',email:'',phone:'',notes:''},documents:[],employees:[],transactions:[],created:new Date().toISOString()}}
function statusFor(date){if(!date)return{type:'valid',label:'بدون تاريخ',days:null};const d=Math.ceil((new Date(`${date}T00:00:00`)-today())/86400000);return d<0?{type:'expired',label:`منتهي منذ ${Math.abs(d)} يوم`,days:d}:d<=90?{type:'soon',label:d===0?'ينتهي اليوم':`متبقي ${d} يوم`,days:d}:{type:'valid',label:'ساري',days:d}}
function esc(s){const d=document.createElement('div');d.textContent=s??'';return d.innerHTML}
function allAlerts(){const rows=state.documents.map(x=>({title:x.title,sub:x.type,date:x.expiry,source:'document',id:x.id}));state.employees.forEach(x=>{if(x.workExpiry)rows.push({title:`تصريح عمل: ${x.name}`,sub:'موظف',date:x.workExpiry,source:'employee',id:x.id});if(x.residenceExpiry)rows.push({title:`إقامة: ${x.name}`,sub:'موظف',date:x.residenceExpiry,source:'employee',id:x.id})});return rows.map(x=>({...x,status:statusFor(x.date)})).filter(x=>x.status.days!==null&&x.status.days<=90).sort((a,b)=>a.status.days-b.status.days)}
function setView(name){$$('.sidebar button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.panel===name));if(innerWidth<900)scrollTo({top:0,behavior:'smooth'})}
function empty(text){return`<div class="empty">${text}</div>`}
function render(){if(!state)return;$('#companySideName').textContent=state.company.name;$('#companySideEmirate').textContent=state.company.emirate;$('#companyInitial').textContent=state.company.name.charAt(0)||'ش';$('#todayLabel').textContent=new Intl.DateTimeFormat('ar-AE',{dateStyle:'full'}).format(new Date());
const alerts=allAlerts(),bad=alerts.filter(x=>x.status.type==='expired').length,warn=alerts.filter(x=>x.status.type==='soon').length,total=Math.max(1,state.documents.length+state.employees.length*2),score=Math.max(0,Math.round(100-(bad*25+warn*8)/total));$('#healthScore').textContent=`${score}%`;$('#healthText').textContent=bad?'توجد التزامات منتهية تحتاج إجراء':warn?'توجد تواريخ تقترب':'لا توجد مخاطر مسجلة';$('#alertCount').textContent=alerts.length;$('#employeeCount').textContent=state.employees.length;$('#transactionCount').textContent=state.transactions.filter(x=>x.status!=='مكتملة'&&x.status!=='ملغاة').length;
$('#alertsList').innerHTML=alerts.slice(0,6).map(x=>`<div class="list-item"><div><b>${esc(x.title)}</b><small>${esc(x.sub)} · ${esc(x.date)}</small></div><span class="badge ${x.status.type}">${x.status.label}</span></div>`).join('')||empty('لا توجد تنبيهات خلال 90 يومًا.');
const tx=[...state.transactions].sort((a,b)=>(b.updated||'').localeCompare(a.updated||''));$('#recentTransactions').innerHTML=tx.slice(0,5).map(x=>`<div class="list-item"><div><b>${esc(x.title)}</b><small>${esc(x.authority||'جهة غير محددة')}</small></div><span class="badge open">${esc(x.status)}</span></div>`).join('')||empty('لم تُضف معاملات بعد.');renderDocuments();renderEmployees();renderTransactions();fillCompany()}
function renderDocuments(){const q=clean($('#documentSearch').value).toLowerCase(),filter=$('#documentStatus').value;const list=state.documents.filter(x=>`${x.title} ${x.type} ${x.number}`.toLowerCase().includes(q)).filter(x=>!filter||statusFor(x.expiry).type===filter);$('#documentsTable').innerHTML=list.map(x=>{const s=statusFor(x.expiry);return`<div class="data-row"><div class="main"><b>${esc(x.title)}</b><small>${esc(x.type||'التزام')} ${x.number?`· ${esc(x.number)}`:''} · ${esc(x.expiry||'بدون تاريخ')}</small></div><div class="meta"><span class="badge ${s.type}">${s.label}</span><button data-edit="document" data-id="${x.id}">تعديل</button><button class="delete" data-delete="document" data-id="${x.id}">حذف</button></div></div>`}).join('')||empty('لا توجد عناصر مطابقة.')}
function renderEmployees(){$('#employeesTable').innerHTML=state.employees.map(x=>{const dates=[x.workExpiry&&`العمل: ${x.workExpiry}`,x.residenceExpiry&&`الإقامة: ${x.residenceExpiry}`].filter(Boolean).join(' · ');return`<div class="data-row"><div class="main"><b>${esc(x.name)}</b><small>${esc(x.role||'بدون مسمى')} ${dates?`· ${esc(dates)}`:''}</small></div><div class="meta"><button data-edit="employee" data-id="${x.id}">تعديل</button><button class="delete" data-delete="employee" data-id="${x.id}">حذف</button></div></div>`}).join('')||empty('أضف الموظفين لمتابعة تواريخ العمل والإقامة.')}
function renderTransactions(){$('#transactionsTable').innerHTML=state.transactions.map(x=>`<div class="data-row"><div class="main"><b>${esc(x.title)}</b><small>${esc(x.authority||'جهة غير محددة')} · ${esc(x.dueDate||'بدون موعد')} ${x.notes?`· ${esc(x.notes)}`:''}</small></div><div class="meta"><span class="badge open">${esc(x.status)}</span><button data-edit="transaction" data-id="${x.id}">تعديل</button><button class="delete" data-delete="transaction" data-id="${x.id}">حذف</button></div></div>`).join('')||empty('أضف المعاملات الجارية لمتابعتها من هنا.')}
function fillCompany(){const f=$('#companyForm');Object.entries(state.company).forEach(([n,v])=>{if(f.elements[n])f.elements[n].value=v||''})}
const fields={document:{title:'التزام أو مستند',collection:'documents',html:'<label>الاسم<input name="title" maxlength="120" required placeholder="مثال: الرخصة التجارية"></label><label>النوع<select name="type"><option>رخصة</option><option>عقد إيجار</option><option>بطاقة منشأة</option><option>ضريبة وامتثال</option><option>تأمين</option><option>مستند آخر</option></select></label><label>الرقم (اختياري)<input name="number" maxlength="80"></label><label>تاريخ الانتهاء<input name="expiry" type="date"></label><label>ملاحظات<input name="notes" maxlength="300"></label>'},employee:{title:'موظف',collection:'employees',html:'<label>اسم الموظف<input name="name" maxlength="100" required></label><label>المسمى الوظيفي<input name="role" maxlength="100"></label><label>انتهاء تصريح العمل<input name="workExpiry" type="date"></label><label>انتهاء الإقامة<input name="residenceExpiry" type="date"></label><label>ملاحظات<input name="notes" maxlength="300"></label>'},transaction:{title:'معاملة',collection:'transactions',html:'<label>اسم المعاملة<input name="title" maxlength="120" required></label><label>الجهة المختصة<input name="authority" maxlength="120"></label><label>الحالة<select name="status"><option>جديدة</option><option>قيد التجهيز</option><option>قيد الإجراء</option><option>بانتظار الشركة</option><option>بانتظار الجهة</option><option>مكتملة</option><option>ملغاة</option></select></label><label>الموعد المستهدف<input name="dueDate" type="date"></label><label>ملاحظات<input name="notes" maxlength="500"></label>'}};
function openDialog(kind,id=''){const def=fields[kind],item=id?state[def.collection].find(x=>x.id===id):null;$('#dialogTitle').textContent=`${item?'تعديل':'إضافة'} ${def.title}`;$('#dialogFields').innerHTML=def.html;const f=$('#itemForm');f.elements.kind.value=kind;f.elements.id.value=id;if(item)Object.entries(item).forEach(([n,v])=>{if(f.elements[n])f.elements[n].value=v||''});$('#itemDialog').showModal()}
async function lock(){state=null;key=null;clearTimeout(lockTimer);$('#workspace').hidden=true;$('#gate').hidden=false;$('#lockBtn').hidden=true;showGate()}
function resetTimer(){if(!state)return;clearTimeout(lockTimer);lockTimer=setTimeout(lock,15*60*1000)}
function showWorkspace(){ $('#gate').hidden=true;$('#workspace').hidden=false;$('#lockBtn').hidden=false;render();resetTimer() }
function showGate(){const v=readVault();$('#newVault').hidden=!!v;$('#openVault').hidden=!v;$('#vaultHint').textContent=v?`الخزنة المسجلة: ${v.hint||'شركة'} · آخر حفظ ${new Date(v.updated).toLocaleString('ar-AE')}`:'';$('#gateMessage').textContent=''}
async function removeVault(){if(!confirm('سيتم حذف جميع بيانات مركز القيادة من هذا الجهاز نهائيًا. هل تريد المتابعة؟'))return;if(!confirm('تأكيد أخير: هل احتفظت بنسخة احتياطية؟'))return;localStorage.removeItem(STORAGE);await lock()}
async function importBackup(file){try{const vault=JSON.parse(await file.text());if(!vault.version||!vault.salt||!vault.iv||!vault.cipher)throw Error();const password=prompt('أدخل كلمة مرور النسخة الاحتياطية للتحقق منها:');if(!password)return;const opened=await decrypt(vault,password);localStorage.setItem(STORAGE,JSON.stringify(vault));state=opened.data;key=opened.derived;showWorkspace();$('#saveState').textContent='تمت استعادة النسخة'}catch{$('#gateMessage').textContent='تعذر فتح النسخة. تحقق من الملف وكلمة المرور.'}}
$('#createForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,p=f.password.value;if(p!==f.confirm.value){$('#gateMessage').textContent='كلمتا المرور غير متطابقتين.';return}try{const salt=crypto.getRandomValues(new Uint8Array(16));key=await derive(p,salt);state=initial(clean(f.company.value),f.emirate.value);localStorage.setItem(STORAGE,JSON.stringify(await encrypt(state,key,salt)));showWorkspace()}catch{$('#gateMessage').textContent='تعذر إنشاء الخزنة في هذا المتصفح.'}});
$('#unlockForm').addEventListener('submit',async e=>{e.preventDefault();try{const opened=await decrypt(readVault(),e.currentTarget.password.value);state=opened.data;key=opened.derived;e.currentTarget.reset();showWorkspace()}catch{$('#gateMessage').textContent='كلمة المرور غير صحيحة أو بيانات الخزنة تالفة.'}});
$('#itemForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),kind=fd.get('kind'),def=fields[kind],id=fd.get('id'),item={id:id||uid(),updated:new Date().toISOString()};for(const [k,v] of fd)if(!['kind','id'].includes(k))item[k]=clean(v);if(id){const i=state[def.collection].findIndex(x=>x.id===id);state[def.collection][i]=item}else state[def.collection].unshift(item);await save();$('#itemDialog').close();render()});
$('#companyForm').addEventListener('submit',async e=>{e.preventDefault();state.company={...state.company,...Object.fromEntries([...new FormData(e.currentTarget)].map(([k,v])=>[k,clean(v)]))};await save();render()});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)setView(b.dataset.view);if(b.dataset.viewJump)setView(b.dataset.viewJump);if(b.dataset.open)openDialog(b.dataset.open);if(b.dataset.edit)openDialog(b.dataset.edit,b.dataset.id);if(b.dataset.delete&&confirm('حذف هذا العنصر؟')){const def=fields[b.dataset.delete];state[def.collection]=state[def.collection].filter(x=>x.id!==b.dataset.id);await save();render()}if(b.matches('[data-close]'))$('#itemDialog').close()});
$('#documentSearch').addEventListener('input',renderDocuments);$('#documentStatus').addEventListener('change',renderDocuments);$('#lockBtn').addEventListener('click',lock);$('#resetAtGate').addEventListener('click',removeVault);$('#deleteVaultBtn').addEventListener('click',removeVault);
$('#exportBtn').addEventListener('click',()=>{const blob=new Blob([localStorage.getItem(STORAGE)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`hossam-bahr-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)});
function chooseBackup(){$('#backupFile').click()}$('#importBtn').addEventListener('click',chooseBackup);$('#importAtGate').addEventListener('click',chooseBackup);$('#backupFile').addEventListener('change',e=>{if(e.target.files[0])importBackup(e.target.files[0]);e.target.value='' });
['click','keydown','touchstart'].forEach(ev=>document.addEventListener(ev,resetTimer,{passive:true}));document.addEventListener('visibilitychange',()=>{if(document.hidden&&state)$('#saveState').textContent='المركز سيُقفل بعد 15 دقيقة من عدم النشاط'});showGate();
})();
