// مرحلة ما قبل النشر: رحلة المستثمر، الباقات، الامتثال، والثقة القانونية.
const servicesSection=document.querySelector('#services');
const advisor=document.createElement('section');advisor.className='section advisor';advisor.id='advisor';advisor.innerHTML=`
<div class="section-title reveal"><div><span>مستشار تأسيس الشركة</span><h2>اعرف المسار الأنسب<br><em>لمشروعك في دقائق</em></h2></div><p>أجب عن أسئلة بسيطة لتحصل على توصية أولية بين البر الرئيسي والمنطقة الحرة مع الخطوة التالية.</p></div>
<div class="advisor-shell"><div class="advisor-progress"><b id="advisorStep">1 من 5</b><span><i id="advisorBar"></i></span></div><form id="advisorForm">
<fieldset class="advisor-page active"><legend>أين سيكون عملاؤك الرئيسيون؟</legend><label><input type="radio" name="market" value="mainland" required><span>داخل دولة الإمارات</span></label><label><input type="radio" name="market" value="freezone"><span>خارج الدولة أو عبر الإنترنت</span></label><label><input type="radio" name="market" value="unsure"><span>داخل وخارج الدولة / غير متأكد</span></label></fieldset>
<fieldset class="advisor-page"><legend>ما طبيعة نشاطك؟</legend><label><input type="radio" name="activity" value="trade" required><span>تجارة أو استيراد وتصدير</span></label><label><input type="radio" name="activity" value="services"><span>استشارات أو خدمات مهنية</span></label><label><input type="radio" name="activity" value="online"><span>تجارة إلكترونية أو تقنية</span></label><label><input type="radio" name="activity" value="regulated"><span>نشاط يحتاج موافقات خاصة</span></label></fieldset>
<fieldset class="advisor-page"><legend>كم تأشيرة تحتاج مبدئيًا؟</legend><label><input type="radio" name="visas" value="0" required><span>لا أحتاج تأشيرات</span></label><label><input type="radio" name="visas" value="1"><span>من 1 إلى 3</span></label><label><input type="radio" name="visas" value="4"><span>4 تأشيرات أو أكثر</span></label></fieldset>
<fieldset class="advisor-page"><legend>هل تحتاج مقرًا فعليًا؟</legend><label><input type="radio" name="office" value="yes" required><span>نعم، مكتب أو محل أو مستودع</span></label><label><input type="radio" name="office" value="flexi"><span>مساحة عمل مرنة تكفيني</span></label><label><input type="radio" name="office" value="unsure"><span>أحتاج مساعدة للاختيار</span></label></fieldset>
<fieldset class="advisor-page"><legend>ما ميزانية التأسيس المتوقعة؟</legend><label><input type="radio" name="budget" value="low" required><span>أقل من 15,000 درهم</span></label><label><input type="radio" name="budget" value="mid"><span>15,000 – 30,000 درهم</span></label><label><input type="radio" name="budget" value="high"><span>أكثر من 30,000 درهم</span></label></fieldset>
<div class="advisor-actions"><button type="button" id="advisorPrev">السابق</button><button type="button" id="advisorNext">التالي</button></div></form><div id="advisorResult" class="advisor-result"></div></div>`;
servicesSection.parentNode.insertBefore(advisor,servicesSection);

const packages=document.createElement('section');packages.className='section packages';packages.innerHTML=`
<div class="section-title reveal"><div><span>حلول حسب احتياجك</span><h2>باقات منظمة<br><em>بلا تفاصيل مخفية</em></h2></div><p>تُحدد الأسعار النهائية بعد مراجعة النشاط والإمارة والموافقات، وتُفصل الرسوم الحكومية عن أتعاب الخدمة.</p></div><div class="package-grid">
<article><small>للبداية الذكية</small><h3>باقة رائد الأعمال</h3><p>للأنشطة المهنية والرقمية الصغيرة.</p><ul><li>استشارة اختيار النشاط</li><li>حجز الاسم والرخصة</li><li>عقد التأسيس عند الحاجة</li><li>قائمة متطلبات الحساب البنكي</li></ul><a href="#quick-request">اطلب عرضًا مفصلًا ←</a></article>
<article class="featured"><small>الأكثر شمولًا</small><h3>باقة المستثمر</h3><p>تأسيس الشركة مع إقامة المستثمر.</p><ul><li>إصدار الرخصة</li><li>بطاقة وملف المنشأة</li><li>إقامة وهوية المستثمر</li><li>توجيه ضريبي وامتثال أولي</li></ul><a href="#quick-request">اطلب عرضًا مفصلًا ←</a></article>
<article><small>للشركات القائمة</small><h3>باقة الامتثال السنوي</h3><p>للحفاظ على الشركة محدثة ومنظمة.</p><ul><li>تقويم الرخصة والإقامات</li><li>تحديث UBO والبيانات</li><li>مراجعة WPS والتوطين</li><li>تنبيهات الضرائب والتجديد</li></ul><a href="#quick-request">اطلب عرضًا مفصلًا ←</a></article></div>`;
document.querySelector('.process').parentNode.insertBefore(packages,document.querySelector('.process'));

const compliance=document.createElement('section');compliance.className='section compliance';compliance.innerHTML=`
<div class="section-title"><div><span>الضرائب والامتثال</span><h2>احمِ شركتك من<br><em>التأخير والغرامات</em></h2></div><p>خدمات مخصصة للشركات الجديدة والقائمة، مع توضيح نطاق الخدمة والجهة الرسمية المختصة.</p></div><div class="compliance-grid">
<article><b>01</b><h3>ضريبة الشركات</h3><p>التسجيل، تعديل البيانات، الإلغاء، الإقرارات وشهادة الموطن الضريبي.</p><a href="#quick-request" data-enh-service="التسجيل في ضريبة الشركات">اطلب الخدمة ←</a></article>
<article><b>02</b><h3>VAT وTRN</h3><p>التسجيل الإلزامي أو الاختياري، الإلغاء، الإقرارات والاسترداد.</p><a href="#quick-request" data-enh-service="التسجيل في ضريبة القيمة المضافة VAT">اطلب الخدمة ←</a></article>
<article><b>03</b><h3>UBO والمستفيد الحقيقي</h3><p>التسجيل والتحديث ومراجعة سجل الشركاء والمساهمين.</p><a href="#quick-request" data-enh-service="تسجيل وتحديث المستفيد الحقيقي UBO">اطلب الخدمة ←</a></article>
<article><b>04</b><h3>AML وgoAML</h3><p>دعم التسجيل والعناية الواجبة KYC وCDD للأنشطة الخاضعة.</p><a href="#quick-request" data-enh-service="خدمات AML وgoAML">اطلب الخدمة ←</a></article></div>
<div class="official-note">المعلومات إرشادية وقد تتغير. يتم التحقق من المتطلبات وفق حالة العميل ومن المصدر الحكومي المختص قبل تقديم المعاملة.</div>`;
document.querySelector('.smart-tools').parentNode.insertBefore(compliance,document.querySelector('.smart-tools'));

const trust=document.createElement('section');trust.className='section legal-trust';trust.innerHTML=`<div><span>شفافية وثقة</span><h2>تعرف على كل خطوة<br><em>قبل أن تبدأ</em></h2></div><div class="trust-cards"><article><b>رسوم واضحة</b><p>نفصل الرسوم الحكومية عن أتعاب إنجاز الخدمة في عرض السعر.</p></article><article><b>مصادر رسمية</b><p>نراجع المتطلبات وفق الجهة الحكومية المختصة وتاريخ آخر تحديث.</p></article><article><b>حماية البيانات</b><p>لا تُستخدم مستندات العميل إلا لمعالجة الخدمة التي طلبها وبموافقته.</p></article></div><p class="private-disclaimer">حسام بحر لخدمات الأعمال شركة خاصة لتقديم خدمات تأسيس الأعمال ومتابعة المعاملات، وليست جهة حكومية ولا تمثل الجهات الحكومية المذكورة في الموقع.</p>`;
document.querySelector('.request').parentNode.insertBefore(trust,document.querySelector('.request'));

// إزالة الأرقام والآراء التجريبية قبل النشر حفاظًا على المصداقية.
document.querySelector('.hero-proof').innerHTML='<div><b>7 إمارات</b><span>نطاق خدمة شامل</span></div><div><b>وضوح</b><span>متطلبات وتكاليف مفصلة</span></div><div><b>متابعة</b><span>من الطلب حتى الإنجاز</span></div>';
document.querySelector('.testimonials')?.remove();
document.querySelector('.request form').insertAdjacentHTML('beforeend','<label class="consent"><input type="checkbox" required> أوافق على <a href="privacy.html" target="_blank">سياسة الخصوصية</a> ومعالجة بياناتي لغرض تنفيذ الطلب.</label>');

let page=0;const pages=[...document.querySelectorAll('.advisor-page')],next=document.querySelector('#advisorNext'),prev=document.querySelector('#advisorPrev');function showPage(){pages.forEach((p,i)=>p.classList.toggle('active',i===page));document.querySelector('#advisorStep').textContent=`${page+1} من ${pages.length}`;document.querySelector('#advisorBar').style.width=`${(page+1)/pages.length*100}%`;prev.style.visibility=page?'visible':'hidden';next.textContent=page===pages.length-1?'اعرض النتيجة':'التالي'}showPage();
next.onclick=()=>{if(!pages[page].querySelector('input:checked')){pages[page].classList.add('needs-answer');return}pages[page].classList.remove('needs-answer');if(page<pages.length-1){page++;showPage();return}const d=Object.fromEntries(new FormData(document.querySelector('#advisorForm'))),mainland=d.market==='mainland'||d.office==='yes'||d.activity==='regulated',result=mainland?'شركة في البر الرئيسي':'شركة في منطقة حرة';document.querySelector('#advisorForm').hidden=true;document.querySelector('#advisorResult').innerHTML=`<span>التوصية الأولية</span><h3>${result}</h3><p>${mainland?'هذا المسار أكثر ملاءمة للعمل المباشر داخل السوق المحلي أو للأنشطة التي تحتاج مقرًا وموافقات خاصة.':'هذا المسار قد يكون مناسبًا لنشاطك الرقمي أو الخارجي مع خيارات مرنة للمكتب والتأشيرات.'}</p><small>هذه توصية إرشادية وليست عرض سعر أو استشارة قانونية نهائية.</small><a href="#quick-request" class="primary-btn">احجز مراجعة مجانية ←</a><button id="restartAdvisor">إعادة الاختبار</button>`;document.querySelector('#restartAdvisor').onclick=()=>{document.querySelector('#advisorForm').reset();document.querySelector('#advisorForm').hidden=false;document.querySelector('#advisorResult').innerHTML='';page=0;showPage()}};prev.onclick=()=>{if(page){page--;showPage()}};
document.querySelectorAll('[data-enh-service]').forEach(a=>a.onclick=()=>{const s=document.querySelector('#requestService');if(![...s.options].some(o=>o.text===a.dataset.enhService))s.add(new Option(a.dataset.enhService,a.dataset.enhService));s.value=a.dataset.enhService});
