(()=>{'use strict';const d=window.HB_KNOWLEDGE,$=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),norm=v=>String(v??'').toLowerCase().normalize('NFKD').replace(/[ًٌٍَُِّْـ]/g,'');
const teamUrl=title=>`https://wa.me/971503780460?text=${encodeURIComponent(`مرحباً، أريد من فريق حسام بحر تجهيز وتنفيذ خدمة: ${title}`)}`;
function serviceCard(x,type){return`<article class="card"><div class="card-top"><span>${esc(x.country||x.authority)}</span><i class="state">${esc(x.status||'متاحة')}</i></div><h3>${esc(x.title)}</h3>${x.summary?`<p>${esc(x.summary)}</p>`:''}${x.requirements?`<ul class="requirements">${x.requirements.slice(0,5).map(r=>`<li>${esc(r)}</li>`).join('')}</ul>`:''}<div class="facts">${x.fee?`<div><small>الرسوم المنشورة</small><b>${esc(x.fee)}</b></div>`:''}${x.duration?`<div><small>المدة</small><b>${esc(x.duration)}</b></div>`:''}</div><small class="card-updated">آخر مراجعة: ${esc(x.updated||d.reviewed)}</small><div class="card-actions">${x.url?`<a class="official" href="${esc(x.url)}" target="_blank" rel="noopener nofollow">المسار الرسمي ↗</a>`:''}<a class="team" href="${teamUrl(x.title)}" target="_blank" rel="noopener">اطلبها من فريقنا</a></div></article>`}
function updateCard(x){return`<article class="update"><time>${esc(x.date)}</time><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><a href="${esc(x.url)}" target="_blank" rel="noopener nofollow">اقرأ المصدر الرسمي ↗</a><footer>${esc(x.authority)} · ${esc(x.impact)} · ${esc(x.status)}</footer></article>`}
$('#updatesGrid').innerHTML=d.updates.map(updateCard).join('');
$('#faqGrid').innerHTML=d.faqs.map((x,i)=>`<article class="faq ${i===0?'open':''}"><button><span>${esc(x.q)}</span><b>${i===0?'−':'+'}</b></button><p>${esc(x.a)}</p></article>`).join('');
$('#problemGrid').innerHTML=d.problems.map(x=>`<article class="problem"><b>${esc(x.problem)}</b><p><span>السبب المحتمل:</span> ${esc(x.cause)}</p><p><span>الحل:</span> ${esc(x.solution)}</p></article>`).join('');
$('#internationalGrid').innerHTML=d.international.map(x=>serviceCard(x,'international')).join('');$('#educationGrid').innerHTML=d.education.map(x=>serviceCard(x,'education')).join('');
document.addEventListener('click',e=>{const b=e.target.closest('.faq button');if(b){const a=b.closest('.faq');a.classList.toggle('open');b.querySelector('b').textContent=a.classList.contains('open')?'−':'+'}});
const indexed=[...d.updates.map(x=>({...x,_type:'update'})),...d.faqs.map(x=>({title:x.q,summary:x.a,authority:x.topic,status:'إجابة',updated:d.reviewed,_type:'answer'})),...d.problems.map(x=>({title:x.problem,summary:`${x.cause} ${x.solution}`,authority:'حل مشكلة',status:'حل إرشادي',updated:d.reviewed,keywords:x.keywords,_type:'answer'})),...d.international.map(x=>({...x,_type:'international'})),...d.education.map(x=>({...x,_type:'education'}))];
function search(){const q=norm($('#knowledgeQuery').value),type=$('#knowledgeType').value;if(!q&&!type){$('#searchResults').hidden=true;return}const list=indexed.filter(x=>(!type||x._type===type)&&(!q||norm([x.title,x.summary,x.authority,x.country,x.problem,x.keywords,x.requirements?.join(' ')].join(' ')).includes(q)));$('#searchResults').hidden=false;$('#hubCount').textContent=`${list.length} نتيجة`;$('#hubResults').innerHTML=list.map(x=>x._type==='update'?updateCard(x):serviceCard(x,x._type)).join('')||'<p>لم نجد نتيجة مطابقة. جرّب وصف المشكلة بكلمات أبسط.</p>';$('#searchResults').scrollIntoView({behavior:'smooth'})}
$('#hubSearch').addEventListener('submit',e=>{e.preventDefault();search()});$('#knowledgeType').addEventListener('change',search);
const incoming=new URLSearchParams(location.search).get('q');if(incoming){$('#knowledgeQuery').value=incoming;search()}
const sources=[['وزارة الموارد البشرية','https://www.mohre.gov.ae/en/media-center/news.aspx'],['الهوية والجنسية ICP','https://icp.gov.ae/media/news-reports/'],['الهيئة الاتحادية للضرائب','https://tax.gov.ae/en/media.centre/news.aspx'],['وزارة التربية والتعليم','https://moe.gov.ae/ar/eservices/pages/default.aspx'],['وزارة الخارجية','https://www.mofa.gov.ae/services/attestation']];$('#officialSources').innerHTML=sources.map(x=>`<a href="${x[1]}" target="_blank" rel="noopener nofollow">${x[0]}<small>فتح المصدر الرسمي ↗</small></a>`).join('');
fetch('official-source-status.json',{cache:'no-store'}).then(r=>r.json()).then(s=>{const checked=new Date(s.checkedAt);$('#sourceChecked').textContent=`آخر فحص آلي: ${isNaN(checked)?d.reviewed:checked.toLocaleString('ar-AE')}`;$('#sourceStatus').innerHTML=(s.sources||[]).map(x=>`<span>${esc(x.name)} · ${x.ok?'متاح':'يتطلب تحققًا يدويًا'}</span>`).join('')||'<span>المصادر تحت المراجعة اليومية</span>'}).catch(()=>{$('#sourceChecked').textContent=`آخر مراجعة بشرية: ${d.reviewed}`;$('#sourceStatus').innerHTML='<span>تعذر قراءة سجل الفحص الآلي</span>'});
})();
