(() => {
 'use strict';
 const english=document.documentElement.lang==='en';const prior=window.HB_UI_T||String;
 const labels={
 'قل لنا النتيجة التي تريد الوصول إليها.':'Describe the outcome you want to achieve.','حوّل هدفك إلى حالة تشغيلية واضحة. النظام ينظم المسار، بينما تظل الإجراءات الحساسة خاضعة لموافقتك.':'Turn your goal into a transaction plan. Sensitive actions remain subject to your approval.','ماذا تريد أن تنجز؟':'What do you want to achieve?','مثال: أريد تأسيس شركة في دبي والحصول على إقامة مستثمر وتوظيف موظفين.':'For example: set up a company in Dubai, obtain investor residence and hire employees.',
 'مركز تشغيل HOSSAM BAHR لإدارة الأهداف والشركات والمعاملات والاستحقاقات من مكان واحد.':'Manage your goals, companies, transactions and obligations in one HOSSAM BAHR workspace.','مركز التشغيل':'Workspace','الدولة':'Country','جارٍ تحميل الدول المتاحة…':'Loading available countries…','الأتمتة':'Automation','الشركات':'Companies','كياناتي':'My organizations','+ إضافة شركة':'+ Add organization','الاسم القانوني':'Legal name','الاسم التجاري':'Trade name','الإمارة':'Emirate','رقم الرخصة / التسجيل':'Licence / registration number','حفظ الشركة':'Save organization','المعاملات المفتوحة':'Open transactions','دليل الخدمات':'Service catalog','60 يومًا':'60 days','مستنداتي':'My documents','+ رفع مستند':'+ Upload document','نوع المستند':'Document type','اختر النوع':'Choose type','جواز سفر':'Passport','إقامة':'Residence','هوية إماراتية':'Emirates ID','رخصة تجارية':'Trade licence','عقد':'Contract','مستند آخر':'Other document','الشركة المرتبطة':'Associated organization','المعاملة المرتبطة':'Associated transaction','تاريخ الانتهاء - إن وجد':'Expiry date, if applicable','الملف':'File','أوافق على تخزين هذا المستند بصورة خاصة واستخدامه في فحص وتجهيز معاملاتي داخل HOSSAM BAHR OS.':'I consent to private storage of this document and its use to review and prepare my transactions within HOSSAM BAHR OS.','التحكم للإنسان أولًا':'You remain in control','لا يسمح النظام للوكيل الذكي باعتماد دفعة، توقيع، إجراء غير قابل للتراجع، أو إرسال خارجي حساس بدون بوابة موافقة مناسبة.':'Payments, signatures, irreversible actions and sensitive external submissions require the appropriate approval.',
 'مستقر':'Stable','يحتاج انتباه':'Needs attention','حرج':'Critical','شركة':'Organization','رقم ':'Number ','حالات مفتوحة':'Open transactions','التزامات':'Obligations','مستندات':'Documents','رخص مرتبطة':'Linked licences','موظفون':'Employees','إقامات':'Residences','عرض Digital Twin':'View organization overview','مؤشر تشغيلي داخلي.':'Internal operational indicator.','الاستحقاقات القادمة':'Upcoming obligations','لا توجد استحقاقات مفتوحة.':'No open obligations.','لا توجد مستندات مرتبطة بالشركة بعد.':'No documents linked to this organization yet.',' • انتهاء ':' • Expires ','المعاملات':'Transactions','لا توجد معاملات مرتبطة بالشركة.':'No transactions linked to this organization.','تعذر تحميل الشركات.':'Organizations could not be loaded.','لا توجد شركة مضافة بعد':'No organizations yet','يمكنك إضافة أول كيان تجاري من هنا.':'Add your first organization here.','اختر الإمارة':'Choose emirate','بدون شركة':'No organization','بدون معاملة':'No transaction',
 'مسودة':'Draft','تجهيز المسار':'Preparing pathway','بانتظارك':'Awaiting you','جاهزة للمراجعة':'Ready for review','معتمدة':'Approved','قيد التنفيذ':'In progress','بانتظار جهة خارجية':'Awaiting an external authority','متوقفة':'Paused','مكتملة':'Completed','ملغاة':'Cancelled','لم تبدأ':'Not started','قيد العمل':'In progress','بانتظار خطوة أخرى':'Awaiting another step','تحتاج موافقة':'Approval required','تم إنشاء المعاملة':'Transaction created','تم إرسال متطلب للمراجعة':'Requirement sent for review','تم تسجيل قرار الموافقة':'Approval decision recorded','اكتملت مراجعة داخلية':'Internal review completed','تم توثيق تنفيذ خارجي':'External execution recorded','تم تجهيز مسار التنفيذ':'Execution pathway prepared','تم تحديث المعاملة':'Transaction updated','فريق التشغيل':'Operations team','المنصة الذكية':'AI assistance','النظام':'System','تكامل خارجي':'External integration','شريك تنفيذ':'Execution partner',
 'اعتماد الخطوة':'Approve step','جارٍ الحفظ…':'Saving…','تم تسجيل الموافقة بأمان.':'Approval recorded securely.','تعذر تسجيل الموافقة الآن. لم يتم تنفيذ أي إجراء خارجي.':'Approval could not be recorded. No external action was executed.','رفض':'Reject','تم تسجيل الرفض وإيقاف المسار عند هذه النقطة.':'Rejection recorded. The pathway is paused at this step.','تعذر تسجيل الرفض الآن.':'Rejection could not be recorded.','إرسال للمراجعة':'Submit for review','تم إرسال المتطلب للمراجعة.':'Requirement sent for review.','تعذر تحديث الخطوة الآن.':'The step could not be updated.','عليك':'Assigned to you','مراجعة المنصة':'Platform review','تنفيذ خارجي':'External execution',' • موافقة صريحة مطلوبة':' • Explicit approval required','المصدر الرسمي':'Official source','لا توجد أحداث مسجلة بعد.':'No recorded events yet.',
 'تحليل HOSSAM BAHR AI':'HOSSAM BAHR AI analysis','تعذر إكمال التحليل الذكي لهذه الحالة حاليًا. لم يتم تنفيذ أي إجراء خارجي.':'AI analysis is unavailable for this transaction. No external action was executed.','يجري تجهيز التحليل الذكي للحالة.':'Preparing AI analysis for this transaction.','تم تحليل الهدف وتجهيز مسار أولي.':'The goal was analysed and an initial pathway prepared.','فهم الطلب:':'Understood goal:','الخطوات المقترحة':'Suggested steps','معلومات نحتاجها':'Information needed','نقاط تحتاج انتباهًا':'Points needing attention','هذه قراءة مساعدة وتحتاج مراجعة بشرية/مصدرية قبل اعتماد أي معلومة تنظيمية أو إجراء حساس.':'This assistance requires human and source review before approving a regulatory fact or sensitive action.','تحليل تمهيدي للمساعدة في تجهيز الحالة؛ لا ينفذ مدفوعات أو توقيعًا أو إرسالًا حكوميًا تلقائيًا.':'Preliminary assistance for preparing your transaction. It does not automatically make payments, sign or submit to government authorities.',
 'اعتماد مطلوب: ':'Approval required: ','مطلوب منك: ':'Action needed from you: ','قيد المراجعة: ':'Under review: ','بانتظار التنفيذ الخارجي: ':'Awaiting external execution: ','المنصة تعالج: ':'Platform processing: ','الخطوة التالية: ':'Next step: ','اكتملت جميع خطوات المسار.':'All pathway steps are completed.','سيتم تحديد الخطوة التالية تلقائيًا.':'The next step will be identified automatically.','تعذر تحميل الحالات.':'Transactions could not be loaded.','لا توجد حالات مفتوحة':'No open transactions','اكتب هدفك بالأعلى أو ابدأ من أي خدمة.':'Enter your goal above or start from a service.',
 'عاجل':'Urgent','مرتفع':'High','عادي':'Normal','منخفض':'Low','فتح لوحة التشغيل':'Open workspace','عرض الاستحقاقات':'View obligations','فتح المعاملة':'Open transaction','تم الاطلاع':'Mark as read','يحتاج انتباهك':'Needs your attention','بدون موعد محدد':'No due date','تعذر تحديث التنبيه الآن.':'This notification could not be updated.','تعذر تحميل Action Inbox':'The action inbox could not be loaded.','ستظل معاملاتك وبقية الأقسام متاحة بشكل طبيعي.':'Your transactions and other sections remain available.','لا يوجد إجراء يحتاج تدخلك الآن':'No action needs your attention','سيظهر هنا كل ما يحتاج موافقتك أو انتباهك بترتيب الأولوية.':'Actions needing your approval or attention appear here in priority order.','تعذر تحميل الاستحقاقات.':'Obligations could not be loaded.','لا توجد استحقاقات مفتوحة':'No open obligations','ستظهر التجديدات والمواعيد المهمة هنا.':'Renewals and important due dates will appear here.',
 'تغيير':'Change','هل تقصد إحدى هذه الخدمات؟ اخترها لفتح المسار الموثق، أو اتركها بدون اختيار لبدء مسار عام.':'Choose a matching service for its verified pathway, or continue without selecting one to start a general pathway.','خدمة موثقة':'Verified service','لا توجد دولة مفعّلة حاليًا':'No active country is available','جاري إنشاء الحالة…':'Creating transaction…','ابدأ الحالة':'Start transaction','تعذر إنشاء الحالة الآن. تأكد من تفعيل Global OS API.':'The transaction could not be created. Your goal has been preserved; please try again.','تم إنشاء الحالة وربطها بالمسار الموثق، وبدأ HOSSAM BAHR AI تحليلها.':'Transaction created and linked to the verified pathway. HOSSAM BAHR AI has started analysing it.','تم إنشاء الحالة في مسار عام آمن، وبدأ HOSSAM BAHR AI تحليلها.':'Transaction created in a general pathway. HOSSAM BAHR AI has started analysing it.','تعذر إضافة الشركة الآن.':'The organization could not be added.',
 'تعذر تحميل المستندات.':'Documents could not be loaded.','الخزنة فارغة':'Your document vault is empty','ارفع المستند مرة واحدة ليصبح جزءًا من ملفك التشغيلي.':'Upload a document to add it to your private workspace.','نوع الملف غير مدعوم. استخدم PDF أو JPG أو PNG أو WEBP.':'Unsupported file type. Use PDF, JPG, PNG or WEBP.','حجم الملف يتجاوز 10 ميجابايت.':'The file exceeds 10 MB.','جاري الرفع الآمن…':'Uploading securely…','رفع إلى الخزنة الخاصة':'Upload to private vault','تعذر رفع الملف إلى الخزنة الخاصة.':'The file could not be uploaded to your private vault.','تم إلغاء الرفع لأن تسجيل المستند لم يكتمل بأمان.':'Upload cancelled because secure document registration could not be completed.','تم حفظ المستند في خزنتك الخاصة. لا يتم إرساله إلى جهة خارجية تلقائيًا.':'Document saved to your private vault. It is not automatically sent to an external authority.',
 'تم نقل سياق محادثتك إلى مركز التشغيل':'Your conversation context has been transferred to your workspace','الخدمة: ':'Service: ','الاختصاص: ':'Jurisdiction: ','الجهة: ':'Authority: ','تم حفظ خطتك وبدء المعاملة من نفس الهدف الذي حللته قبل تسجيل الدخول.':'Your plan was saved and the transaction started with the same goal you analysed before signing in.','تم الاحتفاظ بهدفك، لكن تعذر إنشاء المعاملة الآن. يمكنك المحاولة من زر «ابدأ الحالة».':'Your goal was preserved, but the transaction could not be created. Try the Start transaction button.','مركز التشغيل قيد التفعيل.':'Workspace activation is in progress.','الخدمات الحالية للمنصة مستمرة بشكل طبيعي. سيظهر مركز التشغيل تلقائيًا بعد اكتمال تفعيل البنية الخلفية الآمنة.':'Existing platform services remain available. The workspace will appear when its secure backend is ready.','العودة إلى الخدمات':'Back to services'
 };
 const translate=value=>{const text=String(value);if(!english)return text;if(labels[text]!=null)return labels[text];
 let match=text.match(/^عرض خطة التنفيذ \((\d+) خطوة\)$/);if(match)return 'Execution plan ('+match[1]+' steps)';
 match=text.match(/^سجل المعاملة \((\d+)\)$/);if(match)return 'Transaction history ('+match[1]+')';
 match=text.match(/^(\d+) من (\d+) خطوات مكتملة • (\d+)%$/);if(match)return match[1]+' of '+match[2]+' steps completed • '+match[3]+'%';
 match=text.match(/^جاهزية (\d+)%$/);if(match)return 'Readiness '+match[1]+'%';
 for(const prefix of ['اعتماد مطلوب: ','مطلوب منك: ','قيد المراجعة: ','بانتظار التنفيذ الخارجي: ','المنصة تعالج: ','الخطوة التالية: ','الخدمة: ','الاختصاص: ','الجهة: '])if(text.startsWith(prefix))return labels[prefix]+text.slice(prefix.length);
 return prior(text);
 };
 window.HB_UI_T=translate;
 window.HB_OS_LABELS=Object.freeze({...labels});
 window.HB_OS_HTML=value=>english?String(value).split(/(<[^>]*>)/g).map(part=>part.startsWith('<')?part:part.replace(/^(\s*)(.*?)(\s*)$/s,(_,a,b,c)=>a+translate(b)+c)).join(''):String(value);
})();
