(function(){
  'use strict';
  var data=window.HB_PLATFORM||{services:[],emirates:[]};
  var count=document.querySelector('#publishedCount');
  if(count)count.textContent=String(data.services.length);
  var goalMap={
    establish:{category:'تأسيس الشركات',label:'تأسيس شركة',page:'company-formation-dubai.html',requirements:['هوية أو جواز الشركاء','النشاط والشكل القانوني','خيارات الاسم التجاري']},
    modify:{category:'تعديل الشركات',label:'تعديل شركة أو رخصة',page:'index.html?q=تعديل#discover',requirements:['الرخصة الحالية','وثائق الشركاء أو المدير','قرار التعديل والموافقات']},
    renew:{category:'التجديد والإلغاء',label:'تجديد الرخصة',page:'license-renewal-uae.html',requirements:['الرخصة الحالية','عقد المقر الساري','تسوية المخالفات والموافقات']},
    close:{category:'التجديد والإلغاء',label:'إلغاء أو تصفية شركة',page:'company-liquidation-uae.html',requirements:['قرار الشركاء','تسوية العمال والإقامات','براءات الذمة والإعلان حسب الشكل القانوني']},
    work:{category:'العمل والموظفون',label:'خدمات الموظفين وتصاريح العمل',page:'work-permit-uae.html',official:'https://www.mohre.gov.ae/en/services/services-directory',requirements:['ملف منشأة ساري','جواز الموظف','عرض أو عقد العمل']},
    residence:{category:'الإقامة والهوية',label:'الإقامة والهوية والتأشيرات',page:'residency-identity-dubai.html',official:'https://icp.gov.ae/en/services/interactive-services/',requirements:['جواز ساري','صورة شخصية','بيانات الكفيل أو المنشأة']},
    tax:{category:'الضرائب والامتثال',label:'الضرائب والامتثال',page:'corporate-tax-registration-uae.html',official:'https://tax.gov.ae/en/services.aspx',requirements:['الرخصة ووثائق التأسيس','بيانات الملاك والمخول','بيانات النشاط والفترة المالية']},
    document:{category:'التوثيق الدولي',label:'تصديق مستند',page:'knowledge-hub.html#international',official:'https://www.mofa.gov.ae/services/attestation',requirements:['أصل المستند','تصديقات بلد الإصدار','تحديد بلد الاستخدام']},
    education:{category:'معادلة الشهادات',label:'معادلة أو اعتراف بشهادة',page:'knowledge-hub.html#education',official:'https://moe.gov.ae/en/eservices/pages/default.aspx',requirements:['الشهادة النهائية','كشف الدرجات','التصديقات والترجمة عند الحاجة']}
  };
  var selector=document.querySelector('#serviceSelector');
  selector&&selector.addEventListener('submit',function(event){
    event.preventDefault();
    var type=document.querySelector('#customerType').value,goal=document.querySelector('#serviceGoal').value,emirate=document.querySelector('#serviceEmirate').value,stage=document.querySelector('#journeyStage').value,config=goalMap[goal];
    if(!type||!config||!emirate||!stage)return;
    var matches=data.services.filter(function(item){return item.category===config.category&&(item.emirate===emirate||item.emirate==='اتحادي')});
    var primary=matches[0],officialMatch=matches.find(function(item){return /^https?:/.test(item.url)}),local=data.emirates.find(function(item){return item.name===emirate});
    var official=config.official||local&&local.url||officialMatch&&officialMatch.url||config.page;
    var authority=primary&&primary.authority||local&&local.authority||'الجهة المختصة في الإمارة';
    var stageLabels={starting:'لم تبدأ بعد',documents:'تجهز المستندات',rejected:'واجهت مشكلة أو رفضاً',urgent:'المعاملة عاجلة'};
    var team='https://wa.me/971503780460?text='+encodeURIComponent('مرحباً، أريد تحديد وتجهيز خدمة: '+config.label+' — الفئة: '+(type==='company'?'شركة':'فرد')+' — الإمارة: '+emirate+' — الحالة: '+stageLabels[stage]);
    document.querySelector('#selectorResult').innerHTML='<span>الخدمة الأقرب إلى هدفك</span><h3>'+config.label+' في '+emirate+'</h3><p>هذه الخدمة تنظم الإجراء المطلوب مع '+authority+'. ابدأ بتجهيز الأساسيات، ثم راجع التفاصيل الدقيقة قبل رفع أي مستند.</p><dl><div><dt>وضعك الحالي</dt><dd>'+stageLabels[stage]+'</dd></div><div><dt>المسارات المنشورة</dt><dd>'+(matches.length||1)+' مسار</dd></div><div><dt>المدة المتوقعة</dt><dd>'+(primary&&primary.duration||'تتحدد بعد اختيار المعاملة الدقيقة')+'</dd></div><div><dt>الرسوم</dt><dd>'+(primary&&primary.fee||'تختلف حسب الإمارة والحالة')+'</dd></div></dl><ul>'+config.requirements.map(function(x){return'<li>'+x+'</li>'}).join('')+'</ul><div class="actions"><a href="'+config.page+'">افتح دليل التجهيز ←</a><a href="'+official+'" target="_blank" rel="noopener nofollow">المسار الرسمي ↗</a><a href="'+team+'" target="_blank" rel="noopener">اطلب التنفيذ من فريقنا</a></div>';
  });
  var readinessGoal=document.querySelector('#readinessGoal'),readinessChecklist=document.querySelector('#readinessChecklist');
  readinessGoal&&readinessGoal.addEventListener('change',function(){var config=goalMap[this.value];if(!config){readinessChecklist.innerHTML='<p>اختر المعاملة لإظهار قائمة التجهيز.</p>';return}readinessChecklist.innerHTML=config.requirements.map(function(item,index){return'<label><input type="checkbox" value="'+index+'"><span>'+item+'</span></label>'}).join('')});
  var readiness=document.querySelector('#readinessForm');
  readiness&&readiness.addEventListener('submit',function(event){event.preventDefault();var config=goalMap[readinessGoal.value];if(!config)return;var checks=Array.prototype.slice.call(readinessChecklist.querySelectorAll('input')),ready=checks.filter(function(item){return item.checked}).length,total=checks.length,score=Math.round(ready/total*100),missing=config.requirements.filter(function(item,index){return !checks[index].checked});document.querySelector('#readinessScore').textContent=score+'%';document.querySelector('#readinessBar').style.width=score+'%';var result=document.querySelector('#readinessResult');result.querySelector('h3').textContent=score===100?'ملفك الأولي جاهز للمراجعة':'ينقصك '+missing.length+' من الأساسيات';result.querySelector('p').textContent=score===100?'راجع صلاحية المستندات والتفاصيل الخاصة بإمارتك قبل التقديم.':'جهّز أولاً: '+missing.join('، ')+'. ثم أعد الفحص أو اطلب مراجعة الفريق.';var old=result.querySelector('.readiness-actions');if(old)old.remove();var actions=document.createElement('div');actions.className='actions readiness-actions';actions.innerHTML='<a href="'+config.page+'">افتح دليل التجهيز ←</a><a target="_blank" rel="noopener" href="https://wa.me/971503780460?text='+encodeURIComponent('مرحباً، أريد مراجعة جاهزية ملف '+config.label+'. نسبة الجاهزية الأولية: '+score+'%')+'">اطلب مراجعة الفريق</a>';result.appendChild(actions)});

  function normalize(value){return String(value||'').toLowerCase().replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').replace(/[^\u0600-\u06ffa-z0-9\s]/g,' ').replace(/\s+/g,' ').trim()}
  var assistant=document.querySelector('#assistantForm');
  assistant&&assistant.addEventListener('submit',function(event){event.preventDefault();var raw=document.querySelector('#assistantQuery').value.trim(),query=normalize(raw),terms=query.split(' ').filter(function(x){return x.length>1}),ranked=data.services.map(function(item){var hay=normalize([item.title,item.description,item.category,item.emirate,item.authority].join(' ')),score=terms.reduce(function(sum,term){return sum+(hay.indexOf(term)>-1?1:0)},0);return{item:item,score:score}}).filter(function(row){return row.score>0}).sort(function(a,b){return b.score-a.score}).slice(0,3),container=document.querySelector('#assistantResult');if(!ranked.length){container.innerHTML='<p>لم أجد تطابقاً دقيقاً، لكن لن نتركك دون مسار. جرّب كلمة أبسط مثل «تجديد» أو «موظف» أو «إقامة»، أو <a href="https://wa.me/971503780460?text='+encodeURIComponent('مرحباً، أريد تحديد معاملة: '+raw)+'" target="_blank" rel="noopener">أرسل هدفك للفريق عبر واتساب</a>.</p>';return}container.innerHTML=ranked.map(function(row){var item=row.item,team='https://wa.me/971503780460?text='+encodeURIComponent('مرحباً، أريد المساعدة في خدمة: '+item.title);return'<article class="assistant-match"><small>'+item.category+' · '+item.emirate+'</small><h3>'+item.title+'</h3><p>'+item.description+'</p><footer><a href="'+item.url+'" '+(/^https?:/.test(item.url)?'target="_blank" rel="noopener nofollow"':'')+'>افتح المسار</a><a href="'+team+'" target="_blank" rel="noopener">اطلب التنفيذ</a></footer></article>'}).join('')});
  var fees={
    corporate:{label:'التسجيل في ضريبة الشركات',government:0,note:'الخدمة الحكومية مجانية وفق بطاقة FTA؛ قد توجد أتعاب تجهيز منفصلة.',source:'https://tax.gov.ae/ar/services/corporate.tax.registration.aspx'},
    vat:{label:'التسجيل في ضريبة القيمة المضافة',government:0,note:'الخدمة الحكومية مجانية وفق بطاقة FTA؛ لا يشمل ذلك أتعاب المحاسب أو التجهيز.',source:'https://tax.gov.ae/ar/services/vat.registration.aspx'},
    attestation:{label:'تصديق مستند شخصي لدى وزارة الخارجية',government:150,note:'رسم المستند الشخصي المنشور؛ قد تضاف رسوم توصيل أو قناة.',source:'https://www.mofa.gov.ae/services/attestation'},
    equivalency:{label:'معادلة شهادة ثانوية من خارج الإمارات',government:50,note:'الرسم المنشور للخدمة الأساسية؛ قد تضاف تكاليف تصديق أو ترجمة.',source:'https://moe.gov.ae/en/eservices/servicecard/Pages/CertEquivalent-Out.aspx'},
    tempPermit:{label:'تصريح عمل مؤقت',government:50,note:'رسم الطلب الاتحادي المنشور في بيانات المنصة؛ قد تضاف رسوم إصدار أو قناة حسب الحالة.',source:'https://www.mohre.gov.ae/en/services/temporary-work-permits-2022'},
    residenceRenewal:{label:'تجديد تصريح إقامة — سنة واحدة (تقدير أساسي)',government:300,note:'100 طلب + 100 إصدار لسنة + 100 خدمة ذكية؛ لا يشمل الهوية أو الفحص أو التأمين أو رسوم الحالة.',source:'https://icp.gov.ae/en/services-details/?serviceid=64afe3c1035448005bd52e66'},
    variable:{label:'تأسيس أو تجديد رخصة تجارية',government:null,note:'الرسوم تتغير حسب الإمارة والنشاط والشكل القانوني والموافقات؛ اطلب عرضًا رسميًا قبل الحساب.',source:'uae-service-catalog.html'}
  };
  var feeSelect=document.querySelector('#feeService');
  if(feeSelect)Object.keys(fees).forEach(function(key){var option=document.createElement('option');option.value=key;option.textContent=fees[key].label;feeSelect.appendChild(option)});
  var calculator=document.querySelector('#feeCalculator');
  calculator&&calculator.addEventListener('submit',function(event){event.preventDefault();var item=fees[feeSelect.value];if(!item)return;var service=Math.max(0,Number(document.querySelector('#platformFee').value)||0),gov=item.government;document.querySelector('#governmentFee').textContent=gov===null?'يتطلب عرضًا رسميًا':gov.toLocaleString('ar-AE')+' درهم';document.querySelector('#serviceFee').textContent=service.toLocaleString('ar-AE')+' درهم';document.querySelector('#totalFee').textContent=gov===null?'بعد استلام الرسم الحكومي':(gov+service).toLocaleString('ar-AE')+' درهم';document.querySelector('#feeNote').textContent=item.note;var link=document.querySelector('#feeSource');link.href=item.source;link.hidden=false;});
  var tracking=document.querySelector('#trackingForm');
  tracking&&tracking.addEventListener('submit',function(event){event.preventDefault();var value=document.querySelector('#trackingValue').value.trim();if(!value)return;var link=document.querySelector('#trackingWhatsapp');link.href='https://wa.me/971503780460?text='+encodeURIComponent('مرحباً، أريد متابعة الطلب: '+value);link.textContent='تابع الطلب '+value+' عبر واتساب ←';});
})();
