const categories={
"تأسيس وتطوير الشركات":["تأسيس شركة في دبي","تأسيس شركة في أبوظبي","تأسيس شركة في الشارقة","تأسيس شركة في عجمان","تأسيس شركة في رأس الخيمة","تأسيس شركة في أم القيوين","تأسيس شركة في الفجيرة","تأسيس شركات المناطق الحرة","تأسيس الشركات المهنية","تأسيس المؤسسات الفردية","تأسيس شركات التجارة العامة","تأسيس شركات المقاولات","تأسيس شركات الاستيراد والتصدير","تأسيس شركات التجارة الإلكترونية","تعديل الرخص التجارية","إضافة أو حذف الأنشطة","نقل الملكية","تغيير المدير","فتح ملف المنشأة","فتح بطاقة المنشأة","تجديد الرخص التجارية","تغيير الشكل القانوني للشركة","تحويل المؤسسة إلى شركة","فتح الفروع الجديدة","نقل مقر الشركة","تغيير الاسم التجاري","حجز الأسماء التجارية","تجديد الأسماء التجارية"],
"الإقامات والهوية والأسرة":["إقامة المستثمر","الإقامة الذهبية","إقامة العمل","إقامة الشريك","إقامة الأسرة","إقامة الزوجة والأبناء","إقامة الوالدين","إقامة العامل المنزلي","إقامة فريلانسر","تجديد الإقامة","تعديل الإقامة","إلغاء الإقامة","إصدار الهوية الإماراتية","تجديد الهوية الإماراتية","كفالة الزوجة والأبناء","كفالة الوالدين","تعديل المهنة","استخراج بدل فاقد للهوية","تعديل البيانات الشخصية","رفع وإزالة الغرامات","طلبات الاسترحام"],
"العمل والموارد البشرية":["إصدار عروض العمل","إصدار تصاريح العمل","تجديد تصاريح العمل","إلغاء تصاريح العمل","عقود العمل","عقود الانتقال","تحديث بيانات المنشأة","التوطين","حماية الأجور WPS","تصنيف المنشآت","الاستعلام عن المخالفات","تسوية أوضاع العمال","التسجيل في نظام حماية الأجور WPS","إدارة ملفات الموظفين","إصدار وتجديد بطاقات العمل","خدمات التوطين ونفيس","استشارات الامتثال لقوانين العمل"],
"الهجرة والزيارة والسياحة":["فتح ملفات المنشآت","إصدار التأشيرات","تجديد التأشيرات","إلغاء التأشيرات","كفالة الأسرة","تأشيرات الزيارة","أذونات الدخول","تصحيح الأوضاع","الغرامات والإعفاءات","خدمات الهوية الإماراتية","تأشيرات الزيارة القصيرة","تأشيرات الزيارة الطويلة","تمديد الزيارات","تغيير الوضع داخل الدولة","حجوزات الطيران والفنادق","التأمين الطبي للزوار"],
"المستثمرون والضرائب والامتثال":["فتح الحسابات البنكية للشركات","المساعدة في متطلبات الامتثال البنكي KYC","استخراج الرقم الضريبي TRN","التسجيل في ضريبة القيمة المضافة VAT","تقديم إقرارات ضريبة القيمة المضافة","إلغاء التسجيل الضريبي","التسجيل في ضريبة الشركات","تعديل تسجيل ضريبة الشركات","إلغاء تسجيل ضريبة الشركات","تقديم إقرارات ضريبة الشركات","إصدار شهادة الموطن الضريبي","طلبات إعادة النظر والتوضيحات الضريبية","استشارات المستثمرين ورجال الأعمال","تسجيل وتحديث المستفيد الحقيقي UBO","إدارة سجل الشركاء والمساهمين","التسجيل في نظام goAML","خدمات AML وgoAML","تقييم الامتثال AML/CFT","العناية الواجبة KYC وCDD","تقييم مخاطر العميل","مراجعة الامتثال السنوي","تنبيهات التجديد والالتزامات"],
"الموافقات والخدمات الحكومية":["إيجاري","الكاتب العدل","التصديقات","الموافقات الحكومية","موافقات RTA","موافقات البلدية","موافقات الدفاع المدني","موافقات دائرة الاقتصاد والسياحة","خدمات الأراضي والأملاك","خدمات المحاكم","موافقات بلدية دبي","موافقات هيئة الطرق والمواصلات RTA","موافقات هيئة الصحة DHA","موافقات دائرة الأراضي والأملاك","موافقات هيئة تنظيم العقارات RERA","موافقات الأمن والسلامة","موافقات الأنشطة الطبية","موافقات الأنشطة التعليمية","موافقات الأنشطة السياحية"],
"الكاتب العدل والتصديقات":["الوكالات القانونية","الإقرارات والتعهدات","تصديق العقود","الترجمة القانونية","تصديق المستندات المحلية","تصديق المستندات الدولية"],
"العقارات وإيجاري":["تسجيل عقود الإيجار (إيجاري)","تحديث بيانات إيجاري","خدمات المستثمر العقاري","الإقامة الذهبية العقارية","خدمات نقل الملكية العقارية"],
"تصفية وإلغاء الشركات":["إلغاء الرخص التجارية","تصفية الشركات","إلغاء بطاقة المنشأة","إلغاء التأشيرات","إغلاق الملفات الحكومية","استخراج شهادة إلغاء نهائية"]};
const icons=["▣","◇","◎","◈","⌘","§","⌂","⊘","×"];let active=Object.keys(categories)[0];
const seoPages={"تأسيس شركة في دبي":"company-formation-dubai.html","تأسيس شركات المناطق الحرة":"free-zone-company-uae.html","إقامة المستثمر":"investor-residency-uae.html","الإقامة الذهبية":"golden-residency-uae.html","الإقامة الذهبية العقارية":"golden-residency-uae.html","كفالة الزوجة والأبناء":"family-sponsorship-uae.html","إقامة الزوجة والأبناء":"family-sponsorship-uae.html","التسجيل في ضريبة الشركات":"corporate-tax-registration-uae.html","التسجيل في ضريبة القيمة المضافة VAT":"vat-registration-uae.html","استخراج الرقم الضريبي TRN":"vat-registration-uae.html"};
const grid=document.querySelector('#serviceGrid'),cats=document.querySelector('#serviceCategories'),tabs=document.querySelector('#categoryTabs');
function drawCategories(){const html=Object.keys(categories).map((c,i)=>`<button class="${c===active?'active':''}" data-c="${c}"><i>${icons[i%icons.length]}</i><span>${c}<small>${categories[c].length} خدمة</small></span><b>←</b></button>`).join('');cats.innerHTML=html;tabs.innerHTML=html;document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>{active=b.dataset.c;drawCategories();drawServices()})}
function drawServices(query=''){let list=(query?Object.values(categories).flat():categories[active]).filter(x=>x.includes(query));document.querySelector('#activeCategory').textContent=query?'نتائج البحث':active;document.querySelector('#resultCount').textContent=`${list.length} خدمة`;grid.innerHTML=list.map((s,i)=>`<article class="service-card"><span>${String(i+1).padStart(2,'0')}</span><i>✓</i><h3>${s}</h3><p>إنجاز متكامل للمعاملة مع مراجعة المتطلبات والمتابعة حتى الاستلام.</p>${seoPages[s]?`<a class="service-details" href="${seoPages[s]}">التفاصيل والمتطلبات ←</a>`:`<button data-service="${s}">اطلب الخدمة ←</button>`}</article>`).join('')||'<p class="empty">لم نجد خدمة مطابقة. تواصل معنا وسنساعدك.</p>';document.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>{document.querySelector('#requestService').value=b.dataset.service;location.hash='quick-request'})}
drawCategories();drawServices();document.querySelector('#serviceSearch').oninput=e=>drawServices(e.target.value.trim());
document.querySelectorAll('[data-pillar]').forEach(link=>link.addEventListener('click',()=>{const target=link.dataset.pillar;if(!categories[target])return;active=target;document.querySelector('#serviceSearch').value='';drawCategories();drawServices();setTimeout(()=>document.querySelector('#services').scrollIntoView({behavior:'smooth',block:'start'}),40)}));
const select=document.querySelector('#requestService');Object.values(categories).flat().forEach(s=>select.insertAdjacentHTML('beforeend',`<option>${s}</option>`));
const faqs=[['كم يستغرق تأسيس شركة في الإمارات؟','تختلف المدة حسب الإمارة والنشاط والموافقات المطلوبة، ويمكن إنجاز العديد من الرخص خلال أيام عمل قليلة بعد اكتمال المستندات.'],['هل يمكنني تأسيس شركة دون الإقامة داخل الإمارات؟','نعم، تتوفر خيارات متعددة للمستثمرين من خارج الدولة، ونساعدك في اختيار الشكل القانوني والمنطقة الأنسب.'],['ما المستندات المطلوبة لبدء المعاملة؟','تختلف حسب الخدمة، وغالبًا تبدأ بصورة الجواز والهوية أو التأشيرة. نرسل لك قائمة دقيقة بعد الاستشارة.'],['كيف أعرف حالة معاملتي؟','بعد إرسال الطلب تحصل على رقم معاملة. أدخله في قسم تتبع المعاملة للاطلاع على آخر حالة مسجلة.'],['هل الأسعار تشمل الرسوم الحكومية؟','نوضح في عرض السعر أتعاب الخدمة والرسوم الحكومية كلٌ على حدة لضمان الشفافية الكاملة.']];
document.querySelector('#faqList').innerHTML=faqs.map((f,i)=>`<article><button>${f[0]}<b>${i?'＋':'−'}</b></button><p class="${i?'':'open'}">${f[1]}</p></article>`).join('');document.querySelectorAll('#faqList button').forEach(b=>b.onclick=()=>{const p=b.nextElementSibling;p.classList.toggle('open');b.querySelector('b').textContent=p.classList.contains('open')?'−':'＋'});
function getRequests(){return JSON.parse(localStorage.getItem('hbRequests')||'[]')}function saveRequests(x){localStorage.setItem('hbRequests',JSON.stringify(x))}
document.querySelector('#requestForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),data=Object.fromEntries(fd);data.documents=[...e.target.querySelector('[name="documents"]')?.files||[]].slice(0,5).map(f=>f.name).join('، ');const id=`HB-${new Date().toISOString().slice(2,10).replaceAll('-','')}-${Math.floor(1000+Math.random()*9000)}`;const items=getRequests();items.unshift({...data,id,status:'تم استلام الطلب',date:new Date().toLocaleString('ar-AE'),updated:'سيتم التواصل معك قريبًا لمراجعة المتطلبات.'});saveRequests(items);document.querySelector('#formMessage').innerHTML=`تم استلام طلبك بنجاح. رقم المعاملة: <b>${id}</b>`;e.target.reset()};
document.querySelectorAll('.calculator').forEach(form=>form.onsubmit=e=>{e.preventDefault();const values=[...new FormData(form).values()].map(Number);let total=form.id==='companyCalculator'?values[0]+values[1]+Math.max(0,values[2]-1)*600:(values[0]+values[1])*values[2];form.querySelector('output').innerHTML=`التقدير الأولي: <b>${Math.round(total).toLocaleString('ar-AE')} درهم</b><small>اطلب استشارة للحصول على عرض دقيق</small>`});
document.querySelector('#trackingForm').onsubmit=e=>{e.preventDefault();const id=document.querySelector('#trackingId').value.trim().toUpperCase();const item=getRequests().find(x=>x.id===id);document.querySelector('#trackingResult').innerHTML=item?`<b>${item.status}</b><span>${item.service}</span><p>${item.updated||'طلبك قيد المتابعة.'}</p><small>آخر تحديث: ${item.date}</small>`:`<p class="error">لم نعثر على رقم المعاملة. تأكد من الرقم أو تواصل معنا.</p>`};
document.querySelector('.menu').onclick=()=>document.querySelector('.header nav').classList.toggle('open');document.querySelectorAll('.header nav a').forEach(a=>a.onclick=()=>document.querySelector('.header nav').classList.remove('open'));
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.1});document.querySelectorAll('.reveal').forEach(x=>obs.observe(x));
