(function loadAnalytics(){if(!document.querySelector('script[data-hb-analytics]')){const s=document.createElement('script');s.src='analytics.js';s.defer=true;s.dataset.hbAnalytics='true';document.head.appendChild(s)}})();

const serviceRoutes={
  'company-formation-dubai.html':{authority:'دائرة الاقتصاد والسياحة في دبي (DET)',fee:'تُحسب حسب النشاط والشكل القانوني والموافقات',duration:'تظهر المدة المتوقعة داخل بطاقة الخدمة الرسمية',note:'اختر النشاط والشكل القانوني أولًا حتى تظهر لك التكلفة والمسار الصحيح.',links:[['ابدأ عبر استثمر في دبي','https://www.investindubai.gov.ae/ar/business-setup/business-setup-services']]},
  'free-zone-company-uae.html':{authority:'سلطة المنطقة الحرة التي تختارها',fee:'تختلف باختلاف المنطقة والباقات والتأشيرات',duration:'تختلف باختلاف المنطقة والنشاط',note:'ابدأ بالمقارنة الرسمية، ثم انتقل إلى موقع المنطقة الحرة المختارة للتقديم والسداد.',links:[['قارن مناطق دبي الحرة رسميًا','https://www.investindubai.gov.ae/en/business-setup/free-zone-companies/free-zones-in-dubai-list?category=Free+zones']]},
  'investor-residency-uae.html':{authority:'GDRFA دبي أو ICP لبقية الإمارات',fee:'تختلف حسب الإمارة ونوع الإقامة ومكان مقدم الطلب',duration:'تعرضها بطاقة الخدمة الرسمية قبل التقديم',note:'اختر دبي إذا كانت جهة إصدار إقامتك GDRFA، واختر ICP لبقية الإمارات.',links:[['دبي: إقامة شريك أو مستثمر','https://www.gdrfad.gov.ae/en/services/f52024c6-b812-11ed-5210-4cd98f768936'],['بقية الإمارات: خدمات ICP','https://icp.gov.ae/en/services-details/?serviceid=64afe3c1035448005bd52e64']]},
  'golden-residency-uae.html':{authority:'ICP أو GDRFA دبي حسب الإمارة والفئة',fee:'تختلف حسب الفئة والإمارة ومدة الإقامة',duration:'تختلف حسب الفئة واكتمال إثبات الأهلية',note:'راجع فئتك ومتطلباتها أولًا؛ لا تبدأ طلبًا قبل التأكد من جهة الإمارة ونوع الترشيح.',links:[['تحقق من فئات الإقامة الذهبية عبر ICP','https://icp.gov.ae/services/golden-residency/'],['دبي: افتح دليل خدمات GDRFA','https://www.gdrfad.gov.ae/en/services']]},
  'family-sponsorship-uae.html':{authority:'GDRFA دبي أو ICP لبقية الإمارات',fee:'تختلف حسب الإمارة ومدة الإقامة وحالة المكفول',duration:'تظهر في بطاقة الخدمة الرسمية المختارة',note:'حدد جهة إقامة الكفيل أولًا؛ فهي التي تحدد بوابة التقديم الصحيحة.',links:[['دبي: دليل خدمات GDRFA','https://www.gdrfad.gov.ae/en/services'],['بقية الإمارات: إصدار تصريح إقامة عبر ICP','https://icp.gov.ae/en/services-details/?serviceid=64afe3c1035448005bd52e64']]},
  'corporate-tax-registration-uae.html':{authority:'الهيئة الاتحادية للضرائب (FTA)',fee:'مجانية وفق بطاقة الخدمة الرسمية',duration:'25 دقيقة للتقديم؛ و20 يوم عمل للمراجعة عند اكتمال الطلب',note:'تبدأ الخدمة من بطاقة الهيئة الرسمية ثم تنتقل إلى حسابك في إمارات تاكس.',links:[['افتح بطاقة تسجيل ضريبة الشركات','https://tax.gov.ae/ar/services/corporate.tax.registration.aspx']]},
  'vat-registration-uae.html':{authority:'الهيئة الاتحادية للضرائب (FTA)',fee:'مجانية وفق بطاقة الخدمة الرسمية',duration:'45 دقيقة للتقديم؛ و20 يوم عمل للمراجعة عند اكتمال الطلب',note:'تحقق من بلوغ حد التسجيل ومن صحة مستندات الإيرادات قبل بدء الطلب.',links:[['افتح بطاقة التسجيل في VAT','https://tax.gov.ae/ar/services/vat.registration.aspx']]}
};

const serviceFile=location.pathname.split('/').pop();
const route=serviceRoutes[serviceFile];
const serviceTitle=document.querySelector('h1')?.textContent.replace(/\s+/g,' ').trim()||'هذه الخدمة';
const teamMessage=`مرحباً، أريد من فريق حسام بحر مراجعة وتجهيز ملف خدمة: ${serviceTitle}`;

if(route){
  const links=route.links.map(([label,url])=>`<a href="${url}" target="_blank" rel="noopener nofollow">${label} <b>↗</b></a>`).join('');
  document.querySelector('.hero-service')?.insertAdjacentHTML('afterend',`<section class="choice-center" id="official-route" aria-labelledby="choiceTitle"><div class="choice-heading"><span>ابدأ من هنا · مساران واضحان</span><h2 id="choiceTitle">اختر كيف تريد إنجاز المعاملة</h2><p>يمكنك التقديم بنفسك داخل الموقع الحكومي، أو طلب تجهيز الملف ومراجعته من فريق حسام بحر.</p></div><div class="choice-grid"><article class="official-choice"><i>01</i><span>المسار الحكومي</span><h3>أنجزها بنفسك</h3><p>جهّز المستندات من القائمة في هذه الصفحة، ثم افتح الرابط الرسمي وارفع الأوراق وادفع داخل بوابة الجهة فقط.</p><dl><div><dt>الجهة</dt><dd>${route.authority}</dd></div><div><dt>الرسوم</dt><dd>${route.fee}</dd></div><div><dt>المدة</dt><dd>${route.duration}</dd></div></dl><div class="official-links">${links}</div><small>${route.note}</small></article><article class="team-choice"><i>02</i><span>مسار حسام بحر</span><h3>دعنا نجهّز الملف</h3><p>نحدد الجهة الصحيحة، نراجع المستندات قبل التقديم، ونوضح النواقص والرسوم والخطوة التالية.</p><ul><li>تحديد الخدمة والجهة</li><li>مراجعة المستندات والنواقص</li><li>تجهيز الطلب قبل البوابة الرسمية</li><li>متابعة الخطوات معك</li></ul><a href="https://wa.me/971503780460?text=${encodeURIComponent(teamMessage)}" target="_blank" rel="noopener">اطلب مراجعة الملف عبر واتساب ←</a><small>لا ترسل جوازات أو هويات قبل الاتفاق على قناة آمنة لمعالجة المستندات.</small></article></div><footer>آخر تحقق من الروابط والمعلومات الرسمية: 15 يوليو 2026 · المصدر الرسمي هو المرجع النهائي عند تغير الرسوم أو الشروط.</footer></section>`);
  const heroCta=document.querySelector('.hero-service .cta');
  heroCta?.insertAdjacentHTML('afterend','<a class="official-hero" href="#official-route">أو أنجزها بنفسك رسميًا ↙</a>');
}

document.querySelector('.lead-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),msg=`مرحباً، أود الاستفسار عن ${serviceTitle}. الاسم: ${f.get('name')}، الهاتف: ${f.get('phone')}`;location.href=`https://wa.me/971503780460?text=${encodeURIComponent(msg)}`});
