-- One investor service reviewed against the live GDRFA source on 2026-10-05.
-- Do not compute a fixed total or combine requirements from different investor categories.
do $migration$
declare binding public.hb_service_bindings%rowtype; prior public.hb_policy_versions%rowtype; next_version integer;
begin
 select * into strict binding from public.hb_service_bindings where service_slug='golden-residency-uae' and active and metadata->>'public_catalog'='true';
 select * into strict prior from public.hb_policy_versions where policy_key=binding.policy_key and jurisdiction_id=binding.jurisdiction_id and status='active';
 if prior.reviewed_by='gdrfa_official_review_20261005' then return; end if;
 update public.hb_service_bindings set metadata=coalesce(metadata,'{}'::jsonb)||$golden_metadata${"fees":"رسوم تصريح الإقامة المنشورة 1,100 درهم، ورسوم المعرفة 10 دراهم والابتكار 10 دراهم؛ وتعرض البطاقة 500 درهم للطلب داخل الدولة و20 درهمًا للتوصيل. وتنص على زيادة رسم الإصدار 100 درهم سنويًا عندما تتجاوز الإقامة سنتين. لا يُحسب إجمالي ثابت هنا؛ راجع المبلغ المستحق في المعاملة الرسمية بحسب الحالة.","duration":"5 أيام وفق المدة المتوقعة المنشورة في بطاقة الخدمة الرسمية؛ ولا تمثل ضمانًا للقبول.","lastReviewed":"2026-10-05"}$golden_metadata$::jsonb where id=binding.id;
 update public.hb_policy_versions set status='retired',effective_until=now() where id=prior.id;
 select coalesce(max(version),0)+1 into next_version from public.hb_policy_versions where policy_key=binding.policy_key and jurisdiction_id=binding.jurisdiction_id;
 insert into public.hb_policy_versions(policy_key,jurisdiction_id,version,effective_from,status,rules,source_ids,reviewed_by,reviewed_at,country_pack_id)
 values(binding.policy_key,binding.jurisdiction_id,next_version,now(),'active',$golden_rules$[{"id":"requirement:1","when":[],"effect":"review","reason":"صورة جواز السفر.","actions":["collect_or_verify_requirement"],"sourceRefs":["https://www.gdrfad.gov.ae/en/services/8ea80da4-f43e-11eb-0320-0050569629e8"]},{"id":"requirement:2","when":[],"effect":"review","reason":"للمستثمر أو الشريك في شركة: تقرير مالي معتمد من مكتب تدقيق معتمد داخل الدولة، ورخصة تجارية سارية مع ملحق الشركاء، وكشف حساب الشركة، والتسجيل الضريبي وإيصالات السنة الماضية؛ ولشركات المناطق الحرة شهادة رأس المال وحصة المستثمر ومستندات تراخيص الشركة والمدقق.","actions":["collect_or_verify_requirement"],"sourceRefs":["https://www.gdrfad.gov.ae/en/services/8ea80da4-f43e-11eb-0320-0050569629e8"]},{"id":"requirement:3","when":[],"effect":"review","reason":"لمستثمر الوديعة المالية: إثبات وديعة لا تقل عن 2,000,000 درهم لدى بنك محلي وإثبات السكن في دبي. وتنص الضوابط على شهادة رسمية بتجميد الوديعة لمدة لا تقل عن سنتين واستمرار الاستثمار طوال صلاحية الإقامة.","actions":["collect_or_verify_requirement"],"sourceRefs":["https://www.gdrfad.gov.ae/en/services/8ea80da4-f43e-11eb-0320-0050569629e8"]},{"id":"requirement:4","when":[],"effect":"review","reason":"للمستثمر العقاري: إثبات ملكية عقار أو عقارات بقيمة لا تقل عن 2,000,000 درهم، مع توثيق القيمة لدى دائرة الأراضي والأملاك بدبي؛ وتتبع فئة العقار مراكز التقديم المعتمدة المذكورة في البطاقة الرسمية.","actions":["collect_or_verify_requirement"],"sourceRefs":["https://www.gdrfad.gov.ae/en/services/8ea80da4-f43e-11eb-0320-0050569629e8"]},{"id":"requirement:5","when":[],"effect":"review","reason":"لمستثمر التحصيل الضريبي: خطاب من الهيئة الاتحادية للضرائب يثبت مساهمة ضريبية لا تقل عن 250,000 درهم سنويًا، ورخصة تجارية مع ملحق الشركاء.","actions":["collect_or_verify_requirement"],"sourceRefs":["https://www.gdrfad.gov.ae/en/services/8ea80da4-f43e-11eb-0320-0050569629e8"]},{"id":"conditions","when":[],"effect":"review","reason":"هذه بطاقة خدمة المستثمرين في دبي فقط، وليست مسارًا للمواهب أو العلماء أو رواد الأعمال أو فئات الإقامة الذهبية الأخرى.","actions":["review_conditions"],"sourceRefs":["https://www.gdrfad.gov.ae/en/services/8ea80da4-f43e-11eb-0320-0050569629e8"]},{"id":"special-cases","when":[],"effect":"review","reason":"هذه الخدمة لا تصلح لفئة أخرى من فئات الإقامة الذهبية حتى لو كانت قريبة بالاسم.","actions":["review_special_cases"],"sourceRefs":["https://www.gdrfad.gov.ae/en/services/8ea80da4-f43e-11eb-0320-0050569629e8"]}]$golden_rules$::jsonb,prior.source_ids,'gdrfa_official_review_20261005',now(),prior.country_pack_id);
 update public.hb_policy_sources set last_verified_at=now() where id=any(prior.source_ids) and source_url='https://www.gdrfad.gov.ae/en/services/8ea80da4-f43e-11eb-0320-0050569629e8';
end
$migration$;
